/*
 * test_H7TwoFace_truncate.h
 *
 * Testcases for FileHandle::truncate() through the H7TwoFace facade.
 * Mirror image of test_static_truncate.h, but using two flash pages
 * (mem1/mem2) and the SimpleFs2FlashPages layer.
 *
 * AI generated by GitHub Copilot Claude Opus 4.7 START
 *  Created on: 12.06.2026
 * AI generated by GitHub Copilot Claude Opus 4.7 END
 */
#pragma once

#include <TestUtils.h>
#include <memory>

// AI generated by GitHub Copilot Claude Opus 4.7 START
std::shared_ptr<TestCaseBase<bool>> test_case_static_TwoFace_truncate_enlarge();
std::shared_ptr<TestCaseBase<bool>> test_case_static_TwoFace_truncate_shrink_inline();
std::shared_ptr<TestCaseBase<bool>> test_case_static_TwoFace_truncate_shrink_external();
std::shared_ptr<TestCaseBase<bool>> test_case_static_TwoFace_truncate_shrink_page_to_inline_size();
std::shared_ptr<TestCaseBase<bool>> test_case_static_TwoFace_truncate_to_zero();
// AI generated by GitHub Copilot Claude Opus 4.7 END
