/*
 * test_static_truncate.cc
 *
 * AI generated by GitHub Copilot Claude Opus 4.7 START
 *  Created on: 12.06.2026
 * AI generated by GitHub Copilot Claude Opus 4.7 END
 */
#include "test_static_truncate.h"
#include "../src_2face/H7TwoFaceConfig.h"
#include "../src_2face/SimpleFlashFsNoDel.h"
#include <stderr_exception.h>
#include <format.h>
#include <filesystem>
#include <vector>
#include "../src/sim_pc/SimFlashMemoryPc.h"
#include "../src/dynamic/SimpleFlashFsDynamic.h"
#include "../src_simple_flash_fs_tar/SimpleFlashFsDynamicReadOnly.h"

using namespace Tools;
using namespace SimpleFlashFs::static_memory;
using namespace ::SimpleFlashFs::SimPc;

// AI generated by GitHub Copilot Claude Opus 4.7 START
namespace {

/**
 * Helper carrying everything an inspector wants to assert against.
 * Populated by inspect_file_dynamic() below.
 */
struct InspectFileResult
{
	bool                   found            = false;
	std::size_t            file_len         = 0;
	std::size_t            data_pages_count = 0;
	std::size_t            inode_data_size  = 0;
	std::size_t            free_data_pages  = 0;
	std::vector<std::byte> contents;
};

/**
 * Re-mount `bin_path` via dynamic::SimpleFlashFsReadOnly (the same
 * read-only inspection wrapper used by `simple_flash_fs_tar -i`) and
 * look up `file_name`. Returns geometry observed on the just-flushed
 * on-disk image.
 *
 * The dynamic FS reads page_size / max_inodes etc. from the header so
 * it can inspect files originally written by the static (ConfigH7) FS.
 */
InspectFileResult inspect_file_dynamic( const std::string & bin_path,
                                        const std::string_view & file_name )
{
	InspectFileResult result;

	if( !std::filesystem::exists( bin_path ) ) {
		CPPDEBUG( Tools::format( "inspect: file does not exist: %s", bin_path ) );
		return result;
	}

	SimFlashFsFlashMemory inspect_mem( bin_path );
	// fully qualify to disambiguate from
	// SimpleFlashFs::static_memory::SimpleFlashFs that is pulled in via
	// `using namespace SimpleFlashFs::static_memory`.
	::SimpleFlashFs::dynamic::SimpleFlashFsReadOnly inspect_fs( &inspect_mem );

	if( !inspect_fs.init() ) {
		CPPDEBUG( Tools::format( "inspect: init failed on %s", bin_path ) );
		return result;
	}

	result.free_data_pages = inspect_fs.get_number_of_free_data_pages();

	// pick the LATEST version of the requested file. A flush creates a
	// new inode page (COW) and the old one is only erased lazily, so
	// get_all_inodes() can return multiple versions of the same
	// inode_number with the same file_name. The on-disk current view
	// is the one with the highest inode_version_number.
	decltype( inspect_fs.get_all_inodes( false ) )::value_type latest{};

	for( auto inode : inspect_fs.get_all_inodes( false ) ) {
		if( inode->inode.file_name.empty() ) {
			continue;
		}
		if( inode->inode.file_name != file_name ) {
			continue;
		}
		if( !latest ||
		    inode->inode.inode_version_number >
		        latest->inode.inode_version_number ) {
			latest = inode;
		}
	}

	if( latest ) {
		result.found            = true;
		result.file_len         = latest->inode.file_len;
		result.data_pages_count = latest->inode.data_pages.size();
		result.inode_data_size  = latest->inode.inode_data.size();

		// pull out the actual bytes for content verification
		if( latest->inode.file_len > 0 ) {
			result.contents.resize( latest->inode.file_len );
			latest->seek( 0 );
			std::size_t bytes_read =
				latest->read( result.contents.data(), result.contents.size() );
			result.contents.resize( bytes_read );
		}
	}

	return result;
}

/**
 * Common scaffolding identical to TestCaseOpenBase in test_static_open.cc
 * but lives in this TU so we can run a per-test functor that has full
 * access to both the live fs and the underlying bin file name.
 */
class TestCaseTruncate : public TestCaseBase<bool>
{
public:
	using Func = std::function<bool( SimpleFsNoDel<ConfigH7> & fs,
	                                 const std::string &       bin_file )>;

protected:
	std::optional<SimpleFsNoDel<ConfigH7>>                       fs;
	std::optional<::SimpleFlashFs::SimPc::SimFlashFsFlashMemory> mem;
	std::string                                                  file_name;
	Func                                                         func;

public:
	TestCaseTruncate( const std::string & name_, Func func_ )
	: TestCaseBase<bool>( name_, true ),
	  func( func_ )
	{
		file_name = "." + name + ".bin";
	}

	bool run() override
	{
		if( std::filesystem::exists( file_name ) ) {
			if( !std::filesystem::remove( file_name ) ) {
				throw STDERR_EXCEPTION(
					Tools::format( "cannot delete %s", file_name ) );
			}
		}

		mem.emplace( file_name, SFF_MAX_SIZE );
		fs.emplace( &mem.value() );

		if( !fs->init() ) {
			if( !fs->create() ) {
				throw STDERR_EXCEPTION(
					Tools::format( "cannot create %s", file_name ) );
			}
		}

		bool ret = false;
		try {
			ret = func( *fs, file_name );
		} catch( ... ) {
			fs.reset();
			mem.reset();
			throw;
		}

		// drop the writer first so the file is flushed/closed before
		// the inspector mounts it again in the test body if needed
		fs.reset();
		mem.reset();
		return ret;
	}
};

constexpr const char *  k_test_file_name = "trunc.test";
constexpr std::size_t   k_inline_size    = 100;
constexpr std::size_t   k_inline_grown   = 300;
constexpr std::size_t   k_large_size     = 4 * SFF_PAGE_SIZE + 123; // 5 data pages
constexpr std::size_t   k_shrink_target  = 1 * SFF_PAGE_SIZE + 50;  // 2 data pages

bool check_zero_padding( const std::vector<std::byte> & contents,
                         std::size_t                     from,
                         std::size_t                     to,
                         const char *                    label )
{
	for( std::size_t i = from; i < to; i++ ) {
		if( contents[i] != std::byte( 0 ) ) {
			CPPDEBUG( Tools::format(
				"%s: expected zero at offset %d, got 0x%02X", label, i,
				static_cast<unsigned>( contents[i] ) ) );
			return false;
		}
	}
	return true;
}

bool check_filler( const std::vector<std::byte> & contents,
                   std::size_t                     from,
                   std::size_t                     to,
                   std::byte                       expected,
                   const char *                    label )
{
	for( std::size_t i = from; i < to; i++ ) {
		if( contents[i] != expected ) {
			CPPDEBUG( Tools::format(
				"%s: expected 0x%02X at offset %d, got 0x%02X", label,
				static_cast<unsigned>( expected ), i,
				static_cast<unsigned>( contents[i] ) ) );
			return false;
		}
	}
	return true;
}

} // namespace
// AI generated by GitHub Copilot Claude Opus 4.7 END

// AI generated by GitHub Copilot Claude Opus 4.7 START
/**
 * Enlarge an inline-stored file. Verifies the new bytes are zero-filled
 * and the file is still inline (no external data pages).
 */
std::shared_ptr<TestCaseBase<bool>> test_case_static_truncate_enlarge()
{
	return std::make_shared<TestCaseTruncate>(
		__FUNCTION__,
		[]( SimpleFsNoDel<ConfigH7> & fs, const std::string & bin_file ) {
			{
				auto f = fs.open( k_test_file_name,
				                  std::ios_base::out | std::ios_base::trunc );
				if( !f ) {
					CPPDEBUG( "cannot open file" );
					return false;
				}

				std::vector<std::byte> data( k_inline_size, std::byte( 'A' ) );
				if( f.write( data.data(), data.size() ) != data.size() ) {
					CPPDEBUG( "write failed" );
					return false;
				}

				if( !f.truncate( k_inline_grown ) ) {
					CPPDEBUG( "truncate failed" );
					return false;
				}

				if( f.file_size() != k_inline_grown ) {
					CPPDEBUG( Tools::format( "wrong size after truncate: %d",
					                         f.file_size() ) );
					return false;
				}
				// f goes out of scope: flushes
			}

			auto inspect = inspect_file_dynamic( bin_file, k_test_file_name );
			if( !inspect.found ) {
				CPPDEBUG( "inspect: file not found" );
				return false;
			}
			if( inspect.file_len != k_inline_grown ) {
				CPPDEBUG( Tools::format( "inspect: file_len=%d expected %d",
				                         inspect.file_len, k_inline_grown ) );
				return false;
			}
			if( inspect.data_pages_count != 0 ) {
				CPPDEBUG( Tools::format(
					"inspect: data_pages_count=%d expected 0 (inline)",
					inspect.data_pages_count ) );
				return false;
			}
			if( !check_filler( inspect.contents, 0, k_inline_size,
			                   std::byte( 'A' ), "enlarge original" ) ) {
				return false;
			}
			if( !check_zero_padding( inspect.contents, k_inline_size,
			                         k_inline_grown, "enlarge padding" ) ) {
				return false;
			}
			return true;
		} );
}

/**
 * Shrink an inline-stored file. Verifies file_len matches the new size
 * and content beyond the new end is no longer visible.
 */
std::shared_ptr<TestCaseBase<bool>> test_case_static_truncate_shrink_inline()
{
	return std::make_shared<TestCaseTruncate>(
		__FUNCTION__,
		[]( SimpleFsNoDel<ConfigH7> & fs, const std::string & bin_file ) {
			{
				auto f = fs.open( k_test_file_name,
				                  std::ios_base::out | std::ios_base::trunc );
				if( !f ) {
					return false;
				}

				std::vector<std::byte> data( k_inline_grown,
				                             std::byte( 'B' ) );
				if( f.write( data.data(), data.size() ) != data.size() ) {
					return false;
				}

				if( !f.truncate( k_inline_size ) ) {
					CPPDEBUG( "truncate failed" );
					return false;
				}

				if( f.file_size() != k_inline_size ) {
					return false;
				}
			}

			auto inspect = inspect_file_dynamic( bin_file, k_test_file_name );
			if( !inspect.found ) {
				return false;
			}
			if( inspect.file_len != k_inline_size ) {
				CPPDEBUG( Tools::format( "inspect: file_len=%d expected %d",
				                         inspect.file_len, k_inline_size ) );
				return false;
			}
			if( inspect.data_pages_count != 0 ) {
				CPPDEBUG( Tools::format(
					"inspect: data_pages_count=%d expected 0",
					inspect.data_pages_count ) );
				return false;
			}
			if( inspect.contents.size() != k_inline_size ) {
				CPPDEBUG( Tools::format(
					"inspect: read back %d bytes, expected %d",
					inspect.contents.size(), k_inline_size ) );
				return false;
			}
			if( !check_filler( inspect.contents, 0, k_inline_size,
			                   std::byte( 'B' ),
			                   "shrink_inline content" ) ) {
				return false;
			}
			return true;
		} );
}

/**
 * Shrink a page-stored file. Verifies pages are released to the free
 * pool and the surviving data is still readable.
 */
std::shared_ptr<TestCaseBase<bool>> test_case_static_truncate_shrink_external()
{
	return std::make_shared<TestCaseTruncate>(
		__FUNCTION__,
		[]( SimpleFsNoDel<ConfigH7> & fs, const std::string & bin_file ) {
			std::size_t pages_before = 0;
			std::size_t pages_after  = 0;

			{
				auto f = fs.open( k_test_file_name,
				                  std::ios_base::out | std::ios_base::trunc );
				if( !f ) {
					return false;
				}

				std::vector<std::byte> data( k_large_size, std::byte( 'C' ) );
				if( f.write( data.data(), data.size() ) != data.size() ) {
					return false;
				}
				f.flush();
				pages_before = f.inode.data_pages.size();

				if( pages_before == 0 ) {
					CPPDEBUG( "expected data to land on external pages" );
					return false;
				}

				if( !f.truncate( k_shrink_target ) ) {
					CPPDEBUG( "truncate failed" );
					return false;
				}

				pages_after = f.inode.data_pages.size();

				if( pages_after >= pages_before ) {
					CPPDEBUG( Tools::format(
						"expected pages to shrink, before=%d after=%d",
						pages_before, pages_after ) );
					return false;
				}

				if( f.file_size() != k_shrink_target ) {
					return false;
				}
			}

			auto inspect = inspect_file_dynamic( bin_file, k_test_file_name );
			if( !inspect.found ) {
				return false;
			}
			if( inspect.file_len != k_shrink_target ) {
				CPPDEBUG( Tools::format( "inspect: file_len=%d expected %d",
				                         inspect.file_len, k_shrink_target ) );
				return false;
			}
			if( inspect.data_pages_count != pages_after ) {
				CPPDEBUG( Tools::format(
					"inspect: data_pages_count=%d expected %d",
					inspect.data_pages_count, pages_after ) );
				return false;
			}
			if( inspect.contents.size() != k_shrink_target ) {
				return false;
			}
			if( !check_filler( inspect.contents, 0, k_shrink_target,
			                   std::byte( 'C' ),
			                   "shrink_external content" ) ) {
				return false;
			}
			return true;
		} );
}

/**
 * Write large data on external pages, then truncate to a tiny size
 * that would fit inline. The data stays page-stored (we only trim
 * trailing pages), but file_len shrinks and the visible content
 * matches. Verifies the trim path on pages.
 */
std::shared_ptr<TestCaseBase<bool>>
test_case_static_truncate_shrink_page_to_inline_size()
{
	return std::make_shared<TestCaseTruncate>(
		__FUNCTION__,
		[]( SimpleFsNoDel<ConfigH7> & fs, const std::string & bin_file ) {
			std::size_t pages_before = 0;

			{
				auto f = fs.open( k_test_file_name,
				                  std::ios_base::out | std::ios_base::trunc );
				if( !f ) {
					return false;
				}

				std::vector<std::byte> data( k_large_size, std::byte( 'D' ) );
				if( f.write( data.data(), data.size() ) != data.size() ) {
					return false;
				}
				f.flush();
				pages_before = f.inode.data_pages.size();

				if( pages_before <= 1 ) {
					CPPDEBUG( "expected at least 2 pages before shrink" );
					return false;
				}

				// shrink to something small - 50 bytes
				if( !f.truncate( 50 ) ) {
					return false;
				}

				if( f.file_size() != 50 ) {
					return false;
				}

				// data_pages should be exactly one (covers bytes 0..49)
				if( f.inode.data_pages.size() != 1 ) {
					CPPDEBUG( Tools::format(
						"expected exactly 1 page after shrink, got %d",
						f.inode.data_pages.size() ) );
					return false;
				}
			}

			auto inspect = inspect_file_dynamic( bin_file, k_test_file_name );
			if( !inspect.found ) {
				return false;
			}
			if( inspect.file_len != 50 ) {
				return false;
			}
			if( inspect.data_pages_count != 1 ) {
				CPPDEBUG( Tools::format(
					"inspect: data_pages_count=%d expected 1",
					inspect.data_pages_count ) );
				return false;
			}
			if( inspect.contents.size() != 50 ) {
				return false;
			}
			if( !check_filler( inspect.contents, 0, 50, std::byte( 'D' ),
			                   "shrink page->inline-size content" ) ) {
				return false;
			}
			return true;
		} );
}

/**
 * Truncate-to-zero: empties the file completely. Verifies file_len is
 * 0 and no external pages remain referenced.
 */
std::shared_ptr<TestCaseBase<bool>> test_case_static_truncate_to_zero()
{
	return std::make_shared<TestCaseTruncate>(
		__FUNCTION__,
		[]( SimpleFsNoDel<ConfigH7> & fs, const std::string & bin_file ) {
			{
				auto f = fs.open( k_test_file_name,
				                  std::ios_base::out | std::ios_base::trunc );
				if( !f ) {
					return false;
				}

				std::vector<std::byte> data( k_large_size, std::byte( 'E' ) );
				if( f.write( data.data(), data.size() ) != data.size() ) {
					return false;
				}
				f.flush();

				if( !f.truncate( 0 ) ) {
					CPPDEBUG( "truncate(0) failed" );
					return false;
				}

				if( f.file_size() != 0 ) {
					CPPDEBUG( Tools::format( "expected size 0, got %d",
					                         f.file_size() ) );
					return false;
				}

				if( f.inode.data_pages.size() != 0 ) {
					CPPDEBUG( "expected no data pages after truncate(0)" );
					return false;
				}
			}

			auto inspect = inspect_file_dynamic( bin_file, k_test_file_name );
			if( !inspect.found ) {
				return false;
			}
			if( inspect.file_len != 0 ) {
				return false;
			}
			if( inspect.data_pages_count != 0 ) {
				CPPDEBUG( Tools::format(
					"inspect: data_pages_count=%d expected 0",
					inspect.data_pages_count ) );
				return false;
			}
			if( !inspect.contents.empty() ) {
				return false;
			}
			return true;
		} );
}
// AI generated by GitHub Copilot Claude Opus 4.7 END
