/*
 * test_H7TwoFace_truncate.cc
 *
 * AI generated by GitHub Copilot Claude Opus 4.7 START
 *  Created on: 12.06.2026
 * AI generated by GitHub Copilot Claude Opus 4.7 END
 */
#include "test_H7TwoFace_truncate.h"
#include "../src_2face/H7TwoFace.h"
#include "../src_2face/H7TwoFaceConfig.h"
#include <stderr_exception.h>
#include <format.h>
#include <filesystem>
#include <vector>
#include "../src/sim_pc/SimSTM32InternalFlashPc.h"
#include "../src/dynamic/SimpleFlashFsDynamic.h"
#include "../src_simple_flash_fs_tar/SimpleFlashFsDynamicReadOnly.h"

using namespace Tools;

// AI generated by GitHub Copilot Claude Opus 4.7 START
namespace {

/**
 * Geometry observed from re-mounting one flash page bin via the
 * dynamic, read-only FS (same pattern as `simple_flash_fs_tar -i`).
 */
struct InspectFileResult
{
	bool                   found            = false;
	std::size_t            file_len         = 0;
	std::size_t            data_pages_count = 0;
	std::size_t            inode_data_size  = 0;
	std::size_t            free_data_pages  = 0;
	std::vector<std::byte> contents;
};

/**
 * Mount `bin_path` via dynamic::SimpleFlashFsReadOnly and look up
 * `file_name`. Picks the highest inode_version_number for that name
 * to skip stale COW versions that have not yet been erased.
 */
InspectFileResult inspect_file_dynamic( const std::string &       bin_path,
                                        const std::string_view &  file_name )
{
	InspectFileResult result;

	if( !std::filesystem::exists( bin_path ) ) {
		return result;
	}

	::SimpleFlashFs::SimPc::SimFlashFsFlashMemory inspect_mem( bin_path );
	::SimpleFlashFs::dynamic::SimpleFlashFsReadOnly inspect_fs( &inspect_mem );

	if( !inspect_fs.init() ) {
		return result;
	}

	result.free_data_pages = inspect_fs.get_number_of_free_data_pages();

	decltype( inspect_fs.get_all_inodes( false ) )::value_type latest{};

	for( auto inode : inspect_fs.get_all_inodes( false ) ) {
		if( inode->inode.file_name.empty() ) {
			continue;
		}
		if( inode->inode.file_name != file_name ) {
			continue;
		}
		if( !latest ||
		    inode->inode.inode_version_number >
		        latest->inode.inode_version_number ) {
			latest = inode;
		}
	}

	if( latest ) {
		result.found            = true;
		result.file_len         = latest->inode.file_len;
		result.data_pages_count = latest->inode.data_pages.size();
		result.inode_data_size  = latest->inode.inode_data.size();

		if( latest->inode.file_len > 0 ) {
			result.contents.resize( latest->inode.file_len );
			latest->seek( 0 );
			std::size_t bytes_read =
				latest->read( result.contents.data(), result.contents.size() );
			result.contents.resize( bytes_read );
		}
	}

	return result;
}

/**
 * In the 2-page FS only ONE of the two bin files is currently active
 * (the other is sealed/blank). Try both and return whichever holds
 * our file. Falls back to whichever could even be inspected.
 */
InspectFileResult inspect_active_page( const std::string &      file1,
                                       const std::string &      file2,
                                       const std::string_view & file_name )
{
	auto r1 = inspect_file_dynamic( file1, file_name );
	if( r1.found ) {
		return r1;
	}
	auto r2 = inspect_file_dynamic( file2, file_name );
	if( r2.found ) {
		return r2;
	}
	// neither held the file; return r1 so caller still gets fs stats
	return r1;
}

/**
 * Test-case scaffolding analogous to TestCaseH7Base in test_H7TwoFace.cc
 * but parameterized by a functor that has access to the underlying
 * bin file paths so the inspector can mount them after deinit.
 */
class TestCaseH7Truncate : public TestCaseBase<bool>
{
public:
	using Func = std::function<bool( const std::string & file1,
	                                 const std::string & file2 )>;

protected:
	std::optional<::SimpleFlashFs::SimPc::SimSTM32InternalFlashPc> mem1;
	std::optional<::SimpleFlashFs::SimPc::SimSTM32InternalFlashPc> mem2;
	std::string                                                     file_name;
	std::string                                                     file1;
	std::string                                                     file2;
	Func                                                            func;

public:
	TestCaseH7Truncate( const std::string & name_, Func func_ )
	: TestCaseBase<bool>( name_, true ),
	  file_name( "." + name ),
	  file1( file_name + "_page1.bin" ),
	  file2( file_name + "_page2.bin" ),
	  func( func_ )
	{
	}

	void clear( const std::string & f )
	{
		if( std::filesystem::exists( f ) ) {
			if( !std::filesystem::remove( f ) ) {
				throw STDERR_EXCEPTION(
					Tools::format( "cannot delete %s", f ) );
			}
		}
	}

	bool run() override
	{
		clear( file1 );
		clear( file2 );

		// the 4-arg ctor must be used: it creates/resizes the file
		// (the 3-arg overload would try to open an existing file)
		mem1.emplace( file1, SFF_PAGE_SIZE, SFF_MAX_SIZE, false );
		mem2.emplace( file2, SFF_PAGE_SIZE, SFF_MAX_SIZE, false );
		H7TwoFace::set_memory_interface( &mem1.value(), &mem2.value() );

		bool ret = false;
		try {
			ret = func( file1, file2 );
		} catch( ... ) {
			H7TwoFace::set_memory_interface( nullptr, nullptr );
			mem1.reset();
			mem2.reset();
			throw;
		}

		// detach H7TwoFace so the singleton FS drops its references,
		// then release the flash simulators so their fstream handles
		// are flushed/closed before the inspector reopens the files
		H7TwoFace::set_memory_interface( nullptr, nullptr );
		mem1.reset();
		mem2.reset();
		return ret;
	}
};

// page_size on this side is 512 bytes (SFF_PAGE_SIZE), so the inline
// threshold is around ~400 bytes. Numbers chosen to exercise inline
// vs. external paths cleanly.
constexpr const char *  k_test_file_name = "trunc.test";
constexpr std::size_t   k_inline_size    = 100;
constexpr std::size_t   k_inline_grown   = 300;
constexpr std::size_t   k_large_size     = 4 * SFF_PAGE_SIZE + 123; // 5 pages
constexpr std::size_t   k_shrink_target  = 1 * SFF_PAGE_SIZE + 50;  // 2 pages

bool check_zero_padding( const std::vector<std::byte> & contents,
                         std::size_t                     from,
                         std::size_t                     to,
                         const char *                    label )
{
	for( std::size_t i = from; i < to; i++ ) {
		if( contents[i] != std::byte( 0 ) ) {
			CPPDEBUG( Tools::format(
				"%s: expected zero at offset %d, got 0x%02X", label, i,
				static_cast<unsigned>( contents[i] ) ) );
			return false;
		}
	}
	return true;
}

bool check_filler( const std::vector<std::byte> & contents,
                   std::size_t                     from,
                   std::size_t                     to,
                   std::byte                       expected,
                   const char *                    label )
{
	for( std::size_t i = from; i < to; i++ ) {
		if( contents[i] != expected ) {
			CPPDEBUG( Tools::format(
				"%s: expected 0x%02X at offset %d, got 0x%02X", label,
				static_cast<unsigned>( expected ), i,
				static_cast<unsigned>( contents[i] ) ) );
			return false;
		}
	}
	return true;
}

} // namespace
// AI generated by GitHub Copilot Claude Opus 4.7 END

// AI generated by GitHub Copilot Claude Opus 4.7 START
std::shared_ptr<TestCaseBase<bool>> test_case_static_TwoFace_truncate_enlarge()
{
	return std::make_shared<TestCaseH7Truncate>(
		__FUNCTION__,
		[]( const std::string & file1, const std::string & file2 ) {
			{
				auto f = H7TwoFace::open(
					k_test_file_name,
					std::ios_base::out | std::ios_base::trunc );
				if( !f ) {
					return false;
				}

				std::vector<std::byte> data( k_inline_size, std::byte( 'A' ) );
				if( f->write( data.data(), data.size() ) != data.size() ) {
					return false;
				}

				if( !f->truncate( k_inline_grown ) ) {
					CPPDEBUG( "truncate failed" );
					return false;
				}

				if( f->file_size() != k_inline_grown ) {
					return false;
				}
			}

			auto inspect = inspect_active_page( file1, file2, k_test_file_name );
			if( !inspect.found ) {
				CPPDEBUG( "inspect: file not found in either page" );
				return false;
			}
			if( inspect.file_len != k_inline_grown ) {
				CPPDEBUG( Tools::format(
					"inspect: file_len=%d expected %d", inspect.file_len,
					k_inline_grown ) );
				return false;
			}
			if( inspect.data_pages_count != 0 ) {
				CPPDEBUG( Tools::format(
					"inspect: data_pages_count=%d expected 0 (inline)",
					inspect.data_pages_count ) );
				return false;
			}
			if( !check_filler( inspect.contents, 0, k_inline_size,
			                   std::byte( 'A' ), "twoface enlarge orig" ) ) {
				return false;
			}
			if( !check_zero_padding( inspect.contents, k_inline_size,
			                         k_inline_grown,
			                         "twoface enlarge padding" ) ) {
				return false;
			}
			return true;
		} );
}

std::shared_ptr<TestCaseBase<bool>>
test_case_static_TwoFace_truncate_shrink_inline()
{
	return std::make_shared<TestCaseH7Truncate>(
		__FUNCTION__,
		[]( const std::string & file1, const std::string & file2 ) {
			{
				auto f = H7TwoFace::open(
					k_test_file_name,
					std::ios_base::out | std::ios_base::trunc );
				if( !f ) {
					return false;
				}

				std::vector<std::byte> data( k_inline_grown,
				                             std::byte( 'B' ) );
				if( f->write( data.data(), data.size() ) != data.size() ) {
					return false;
				}

				if( !f->truncate( k_inline_size ) ) {
					return false;
				}
				if( f->file_size() != k_inline_size ) {
					return false;
				}
			}

			auto inspect = inspect_active_page( file1, file2, k_test_file_name );
			if( !inspect.found ) {
				return false;
			}
			if( inspect.file_len != k_inline_size ) {
				CPPDEBUG( Tools::format( "inspect: file_len=%d expected %d",
				                         inspect.file_len, k_inline_size ) );
				return false;
			}
			if( inspect.data_pages_count != 0 ) {
				CPPDEBUG( Tools::format(
					"inspect: data_pages_count=%d expected 0",
					inspect.data_pages_count ) );
				return false;
			}
			if( inspect.contents.size() != k_inline_size ) {
				return false;
			}
			if( !check_filler( inspect.contents, 0, k_inline_size,
			                   std::byte( 'B' ),
			                   "twoface shrink_inline content" ) ) {
				return false;
			}
			return true;
		} );
}

std::shared_ptr<TestCaseBase<bool>>
test_case_static_TwoFace_truncate_shrink_external()
{
	return std::make_shared<TestCaseH7Truncate>(
		__FUNCTION__,
		[]( const std::string & file1, const std::string & file2 ) {
			{
				auto f = H7TwoFace::open(
					k_test_file_name,
					std::ios_base::out | std::ios_base::trunc );
				if( !f ) {
					return false;
				}

				std::vector<std::byte> data( k_large_size, std::byte( 'C' ) );
				if( f->write( data.data(), data.size() ) != data.size() ) {
					return false;
				}
				f->flush();

				if( !f->truncate( k_shrink_target ) ) {
					return false;
				}
				if( f->file_size() != k_shrink_target ) {
					return false;
				}
			}

			auto inspect = inspect_active_page( file1, file2, k_test_file_name );
			if( !inspect.found ) {
				return false;
			}
			if( inspect.file_len != k_shrink_target ) {
				CPPDEBUG( Tools::format( "inspect: file_len=%d expected %d",
				                         inspect.file_len,
				                         k_shrink_target ) );
				return false;
			}
			// expect exactly ceil(target/page_size) data pages
			std::size_t expected_pages =
				( k_shrink_target + SFF_PAGE_SIZE - 1 ) / SFF_PAGE_SIZE;
			if( inspect.data_pages_count != expected_pages ) {
				CPPDEBUG( Tools::format(
					"inspect: data_pages_count=%d expected %d",
					inspect.data_pages_count, expected_pages ) );
				return false;
			}
			if( inspect.contents.size() != k_shrink_target ) {
				return false;
			}
			if( !check_filler( inspect.contents, 0, k_shrink_target,
			                   std::byte( 'C' ),
			                   "twoface shrink_external content" ) ) {
				return false;
			}
			return true;
		} );
}

std::shared_ptr<TestCaseBase<bool>>
test_case_static_TwoFace_truncate_shrink_page_to_inline_size()
{
	return std::make_shared<TestCaseH7Truncate>(
		__FUNCTION__,
		[]( const std::string & file1, const std::string & file2 ) {
			{
				auto f = H7TwoFace::open(
					k_test_file_name,
					std::ios_base::out | std::ios_base::trunc );
				if( !f ) {
					return false;
				}

				std::vector<std::byte> data( k_large_size, std::byte( 'D' ) );
				if( f->write( data.data(), data.size() ) != data.size() ) {
					return false;
				}
				f->flush();

				if( !f->truncate( 50 ) ) {
					return false;
				}
				if( f->file_size() != 50 ) {
					return false;
				}
			}

			auto inspect = inspect_active_page( file1, file2, k_test_file_name );
			if( !inspect.found ) {
				return false;
			}
			if( inspect.file_len != 50 ) {
				return false;
			}
			// expect exactly one page (covers bytes 0..49)
			if( inspect.data_pages_count != 1 ) {
				CPPDEBUG( Tools::format(
					"inspect: data_pages_count=%d expected 1",
					inspect.data_pages_count ) );
				return false;
			}
			if( inspect.contents.size() != 50 ) {
				return false;
			}
			if( !check_filler( inspect.contents, 0, 50, std::byte( 'D' ),
			                   "twoface page->inline-size content" ) ) {
				return false;
			}
			return true;
		} );
}

std::shared_ptr<TestCaseBase<bool>> test_case_static_TwoFace_truncate_to_zero()
{
	return std::make_shared<TestCaseH7Truncate>(
		__FUNCTION__,
		[]( const std::string & file1, const std::string & file2 ) {
			{
				auto f = H7TwoFace::open(
					k_test_file_name,
					std::ios_base::out | std::ios_base::trunc );
				if( !f ) {
					return false;
				}

				std::vector<std::byte> data( k_large_size, std::byte( 'E' ) );
				if( f->write( data.data(), data.size() ) != data.size() ) {
					return false;
				}
				f->flush();

				if( !f->truncate( 0 ) ) {
					return false;
				}
				if( f->file_size() != 0 ) {
					return false;
				}
			}

			auto inspect = inspect_active_page( file1, file2, k_test_file_name );
			if( !inspect.found ) {
				return false;
			}
			if( inspect.file_len != 0 ) {
				return false;
			}
			if( inspect.data_pages_count != 0 ) {
				CPPDEBUG( Tools::format(
					"inspect: data_pages_count=%d expected 0",
					inspect.data_pages_count ) );
				return false;
			}
			if( !inspect.contents.empty() ) {
				return false;
			}
			return true;
		} );
}
// AI generated by GitHub Copilot Claude Opus 4.7 END
