/*
 * test_static_truncate.h
 *
 * Testcases for FileHandle::truncate() on the static SimpleFlashFs.
 * Each test exercises a specific path of the truncate implementation:
 *   - enlarge an inline file
 *   - shrink an inline file
 *   - shrink a page-stored file (still page-stored after)
 *   - shrink a page-stored file down to a size that would fit inline
 *   - truncate to zero
 *
 * After the in-process modifications, every test re-mounts the
 * resulting bin file with dynamic::SimpleFlashFsReadOnly (the same
 * pattern as the -i option of simple_flash_fs_tar) and inspects the
 * allocated inode to confirm the on-disk geometry.
 *
 * AI generated by GitHub Copilot Claude Opus 4.7 START
 *  Created on: 12.06.2026
 * AI generated by GitHub Copilot Claude Opus 4.7 END
 */
#pragma once

#include <TestUtils.h>
#include <memory>

// AI generated by GitHub Copilot Claude Opus 4.7 START
std::shared_ptr<TestCaseBase<bool>> test_case_static_truncate_enlarge();
std::shared_ptr<TestCaseBase<bool>> test_case_static_truncate_shrink_inline();
std::shared_ptr<TestCaseBase<bool>> test_case_static_truncate_shrink_external();
std::shared_ptr<TestCaseBase<bool>> test_case_static_truncate_shrink_page_to_inline_size();
std::shared_ptr<TestCaseBase<bool>> test_case_static_truncate_to_zero();
// AI generated by GitHub Copilot Claude Opus 4.7 END
