/*
 * test_vfs.cc
 *
 * Test runner for the two-drive VFS server. Mirrors the structure of
 * test_static.cc / test_2face.cc but works on top of the same
 * SimpleFlashFsThreadedVfsServer + FramFsImplDetail used by
 * two_drives_dynamic.
 *
 * AI generated by GitHub Copilot Claude Opus 4.7 START
 *  Created on: 12.06.2026
 * AI generated by GitHub Copilot Claude Opus 4.7 END
 */
#include "ColoredOutput.h"
#include "ColBuilder.h"
#include <arg.h>
#include <iostream>
#include <OutDebug.h>
#include <memory>
#include <format.h>
#include "test_vfs_commands.h"
#include "test_mrdb_write_entry.h"
#include <set>
#include <string_utils.h>

using namespace Tools;

// AI generated by GitHub Copilot Claude Opus 4.7 START
int main( int argc, char ** argv )
{
	ColoredOutput co;

	Arg::Arg arg( argc, argv );
	arg.addPrefix( "-" );
	arg.addPrefix( "--" );

	Arg::OptionChain oc_info;
	arg.addChainR( &oc_info );
	oc_info.setMinMatch( 1 );
	oc_info.setContinueOnMatch( false );
	oc_info.setContinueOnFail( true );

	Arg::FlagOption o_help( "help" );
	o_help.setDescription( "Show this page" );
	oc_info.addOptionR( &o_help );

	Arg::FlagOption o_debug( "d" );
	o_debug.addName( "debug" );
	o_debug.setDescription( "print debugging messages" );
	o_debug.setRequired( false );
	arg.addOptionR( &o_debug );

	Arg::IntOption o_testcase( "t" );
	o_testcase.addName( "testcase" );
	o_testcase.setDescription( "run testcase 1 2 ..." );
	o_testcase.setRequired( false );
	arg.addOptionR( &o_testcase );

	if( !arg.parse() ) {
		std::cout << arg.getHelp( 5, 20, 30, 80 ) << std::endl;
		return 1;
	}

	if( o_debug.getState() ) {
		Tools::x_debug = new OutDebug();
	}

	if( o_help.getState() ) {
		std::cout << arg.getHelp( 5, 20, 30, 80 ) << std::endl;
		return 1;
	}

#if __cpp_exceptions > 0
	try {
#endif

		std::vector<std::shared_ptr<TestCaseBase<bool>>> test_cases;

		// One test per command; format() runs first so anything that
		// depends on a mounted fs has a clean slate.
		test_cases.push_back( test_case_vfs_format() );
		test_cases.push_back( test_case_vfs_pwd() );
		test_cases.push_back( test_case_vfs_cd() );
		test_cases.push_back( test_case_vfs_dos_change_drive() );
		test_cases.push_back( test_case_vfs_touch() );
		test_cases.push_back( test_case_vfs_ls_empty() );
		test_cases.push_back( test_case_vfs_ls_after_touch() );
		test_cases.push_back( test_case_vfs_dir_alias() );
		test_cases.push_back( test_case_vfs_test_count() );
		test_cases.push_back( test_case_vfs_cat() );
		test_cases.push_back( test_case_vfs_cp_same_drive() );
		test_cases.push_back( test_case_vfs_cp_cross_drive() );
		test_cases.push_back( test_case_vfs_mv_rename() );
		test_cases.push_back( test_case_vfs_rm() );
		test_cases.push_back( test_case_vfs_help() );
		test_cases.push_back( test_case_vfs_quit() );
		test_cases.push_back( test_case_vfs_cleanup() );
		test_cases.push_back( test_case_vfs_test1_full_flow() );
		test_cases.push_back( test_case_vfs_two_threads_same_drive_no_lock() );
		test_cases.push_back( test_case_vfs_two_threads_same_file_open_twice() );
		test_cases.push_back( test_case_vfs_writer_and_tail_reader() );
		test_cases.push_back( test_case_mrdb_write_entry_basic() );
		test_cases.push_back( test_case_mrdb_write_entry_overwrite() );
		test_cases.push_back( test_case_mrdb_write_entry_multiple_slots() );

		ColBuilder col;

		const int COL_IDX       = col.addCol( "Idx" );
		const int COL_NAME      = col.addCol( "Test" );
		const int COL_RESULT    = col.addCol( "Result" );
		const int COL_EXPTECTED = col.addCol( "Expected" );
		const int COL_TEST_RES  = col.addCol( "Test Result" );

		unsigned idx             = 0;
		bool     something_failed = false;

		std::set<int> these_testcases_only;
		for( auto & v : *o_testcase.getValues() ) {
			these_testcases_only.insert( s2x<int>( v, 0 ) );
		}

		for( auto & test : test_cases ) {
			idx++;

			if( !these_testcases_only.empty() ) {
				if( !these_testcases_only.count( idx ) ) {
					continue;
				}
			}

			CPPDEBUG( Tools::format( "run test: %s", test->getName() ) );

			col.addColData( COL_IDX, Tools::format( "% 2d", idx ) );
			col.addColData( COL_NAME, test->getName() );

			std::string result;
			std::string expected_result = test->getExpectedResult() ? "true" : "false";
			std::string test_result;

#if __cpp_exceptions > 0
			try {
#endif
				if( test->throwsException() ) {
					expected_result = "exception";
				}

				result = test->run() ? "true" : "false";

#if __cpp_exceptions > 0
			} catch( const std::exception & error ) {
				result = "exception";
				CPPDEBUG( Tools::format( "Error: %s", error.what() ) );
			} catch( ... ) {
				result = "exception";
				CPPDEBUG( "Error" );
			}
#endif

			if( result != expected_result ) {
				test_result      = co.color_output( ColoredOutput::RED, "failed" );
				something_failed = true;
			} else {
				test_result =
					co.color_output( ColoredOutput::GREEN, "succeeded" );
			}

			col.addColData( COL_RESULT, result );
			col.addColData( COL_EXPTECTED, expected_result );
			col.addColData( COL_TEST_RES, test_result );
		}

		std::cout << col.toString() << std::endl;

		if( something_failed ) {
			std::cout << "Complete result: "
			          << co.color_output( ColoredOutput::RED, "FAILED!!" )
			          << std::endl;
			return 1;
		} else {
			std::cout << "Complete result: "
			          << co.color_output( ColoredOutput::GREEN, "succeeded" )
			          << std::endl;
		}

#if __cpp_exceptions > 0
	} catch( const std::exception & error ) {
		std::cout << "Error: " << error.what() << std::endl;
		return 1;
	}
#endif

	return 0;
}
// AI generated by GitHub Copilot Claude Opus 4.7 END
