/*
 * test_vfs_setup.h
 *
 * Shared 2-drive setup used by every test_vfs test case. Mirrors the
 * drive geometry of two_drives_dynamic so the tests exercise the
 * same code paths the user actually runs.
 *
 * AI generated by GitHub Copilot Claude Opus 4.7 START
 *  Created on: 12.06.2026
 * AI generated by GitHub Copilot Claude Opus 4.7 END
 */
#pragma once

#include <TestUtils.h>
#include <memory>
#include <optional>
#include <string>
#include <vector>
#include <cstddef>
#include <functional>

#include <SimpleFlashFsDynamic.h>
#include "../simpleflashfs/src/sim_pc/SimFlashMemoryPc.h"
#include "../simpleflashfs/src_vfs/SimpleFlashFsVfsServer.h"
#include "../simpleflashfs/src_vfs/FramFsImplDetail.h"
#include "../simpleflashfs/src_vfs/CommandParser.h"
#include "../simpleflashfs/src_vfs/FilesystemCommands.h"
#include "../simpleflashfs/src_vfs/TestCommands.h"

// AI generated by GitHub Copilot Claude Opus 4.7 START
namespace test_vfs {

// Same geometry as in two_drives_dynamic (simpleflashfs/src_vfs/main.cc).
constexpr uint32_t DRIVE_A_FM_25_W_256_SIZE      = 0x00007FFF + 1;
constexpr uint32_t DRIVE_A_FM_25_W_256_PAGE_SIZE = 256;

constexpr uint32_t DRIVE_B_AT45_DB321E_SIZE      = 32'000'000 / 8;
constexpr uint32_t DRIVE_B_AT45_DB321E_PAGE_SIZE = 528;

/**
 * Drive A: small FRAM-style drive (32KB / 256B pages).
 */
class FramFsDriveA : public FramFsImplDetail
{
public:
	FramFsDriveA( ::SimpleFlashFs::FlashMemoryInterface * mem_interface_ )
	: FramFsImplDetail( mem_interface_, "a" )
	{
	}

	void create() override;
};

/**
 * Drive B: larger AT45-style drive (~4MB / 528B pages).
 */
class FramFsDriveB : public FramFsImplDetail
{
public:
	FramFsDriveB( ::SimpleFlashFs::FlashMemoryInterface * mem_interface_ )
	: FramFsImplDetail( mem_interface_, "b" )
	{
	}

	void create() override;
};

/**
 * Holds the two simulated flash chips plus the VFS server and the
 * command parser. Constructed fresh for every test case so each test
 * starts from a known clean state.
 */
struct VfsFixture
{
	std::string drive_a_path;
	std::string drive_b_path;

	std::shared_ptr<::SimpleFlashFs::FlashMemoryInterface>  mem_drive_a;
	std::shared_ptr<::SimpleFlashFs::FlashMemoryInterface>  mem_drive_b;

	std::shared_ptr<FramFsDriveA>                            drive_a;
	std::shared_ptr<FramFsDriveB>                            drive_b;

	std::shared_ptr<SimpleFlashFs::Vfs::VfsServerInterface> vfs;
	std::shared_ptr<SimpleFlashFs::Vfs::CommandParser>      parser;

	/**
	 * Create the simulator bin files (deleting any leftovers from
	 * previous runs), register both drives with the VFS server,
	 * start the server, and register every built-in command from
	 * two_drives_dynamic's main.cc.
	 */
	explicit VfsFixture( const std::string & name_prefix );

	/**
	 * Stops the server, releases drives and memory, deletes the bin
	 * files so the next test starts from scratch.
	 */
	~VfsFixture();

	/**
	 * Run a semicolon-separated command sequence, identical to how
	 * two_drives_dynamic processes its -c argument. The combined
	 * output (concatenated `result.output`) is returned; if any
	 * command fails the test caller should check the boolean.
	 */
	struct CmdSeqResult {
		bool        all_ok = true;
		std::string output;
		std::string last_error;
	};
	CmdSeqResult run( const std::string & cmd_sequence );

	/**
	 * Reach into the registered drive object and force a re-init
	 * after the underlying bin file has been changed externally
	 * (we never do that in these tests, but exposing it keeps the
	 * fixture honest).
	 */
	bool reinit_drive( const std::string & drive_name );
};

/**
 * Result of inspecting a drive bin file via dynamic::SimpleFlashFsReadOnly.
 * `inspect_drive()` returns one of these.
 */
struct DriveInspect
{
	struct InodeView {
		std::string            file_name;
		std::size_t            file_len         = 0;
		std::size_t            data_pages_count = 0;
		std::size_t            inode_data_size  = 0;
		uint64_t               inode_number     = 0;
		uint64_t               inode_version    = 0;
		uint32_t               page             = 0;
		std::vector<std::byte> contents;        // only filled on demand
	};

	bool                     mounted        = false;
	std::size_t              free_data_pages = 0;
	std::vector<InodeView>   inodes;          // every non-empty, latest-version inode
};

/**
 * Mount the underlying bin file of `drive_name` (in `fix`) using
 * ::SimpleFlashFs::dynamic::SimpleFlashFsReadOnly, the same approach
 * `simple_flash_fs_tar -i` uses, and report the live inode layout.
 * Only the LATEST version of each filename is returned (COW leaves
 * older inode versions on disk until lazy erase).
 *
 * If `pull_contents` is true the file bytes are also read into
 * InodeView::contents for content-level assertions.
 */
DriveInspect inspect_drive( const VfsFixture & fix,
                            const std::string & drive_name,
                            bool                pull_contents = true );

/**
 * Convenience: locate one named file in a DriveInspect result.
 * Returns nullptr if not present.
 */
const DriveInspect::InodeView * find_file( const DriveInspect & info,
                                           const std::string_view & name );

/**
 * Helper for content assertions in the test bodies. Returns true if
 * the byte ranges match. Logs via CPPDEBUG on mismatch.
 */
bool bytes_equal( const std::vector<std::byte> & got,
                  const std::string_view &       expected,
                  const char *                   label );

} // namespace test_vfs
// AI generated by GitHub Copilot Claude Opus 4.7 END
