/*
 * test_vfs_commands.h
 *
 * One TestCase per registered command in two_drives_dynamic.
 *
 * AI generated by GitHub Copilot Claude Opus 4.7 START
 *  Created on: 12.06.2026
 * AI generated by GitHub Copilot Claude Opus 4.7 END
 */
#pragma once

#include <TestUtils.h>
#include <memory>

// AI generated by GitHub Copilot Claude Opus 4.7 START
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_format();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_pwd();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_cd();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_dos_change_drive();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_touch();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_ls_empty();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_ls_after_touch();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_dir_alias();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_test_count();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_cat();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_cp_same_drive();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_cp_cross_drive();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_mv_rename();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_rm();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_help();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_quit();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_cleanup();
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_test1_full_flow();
// AI generated by GitHub Copilot Claude Opus 4.7 END
