/*
 * test_mrdb_write_entry.cc
 *
 * Tests for the write_entry() mechanism used by
 * Measurement_Result_Database_v3::write_entry() from
 * SVM_1001_Measurement_Application/Memory/Measurement_Result_Database_v3.cpp
 *
 * write_entry() opens a VFS file at "/b/measurements/<slot>.ini", wraps it
 * in a FileBuffer, then uses SimpleIni to write three INI sections:
 *   [dict]   - status, id, name, time, exported
 *   [cfg]    - guid, target_temperature, dozens of calibration fields
 *   [result] - res_status, res_abort, timestamps, measurement values,
 *              per-sub-determination records
 *
 * These tests replicate that pattern end-to-end on a real VFS fixture
 * so that the on-flash serialisation / deserialisation round-trip is
 * covered independently of the SVM application types.
 *
 * AI generated by GitHub Copilot Claude Sonnet 4.6 START
 *  Created on: 30.06.2026
 * AI generated by GitHub Copilot Claude Sonnet 4.6 END
 */

#include "test_mrdb_write_entry.h"
#include "test_vfs_setup.h"
#include "../src_2face/SimpleIni.h"
#include "../src_2face/SimpleFlashFsFileBuffer.h"
#include <CpputilsDebug.h>
#include <format.h>
#include <string_utils.h>
#include <vector>
#include <cstring>

using namespace Tools;
using namespace test_vfs;

// AI generated by GitHub Copilot Claude Sonnet 4.6 START
namespace {

// ---------------------------------------------------------------------------
// TestCaseVfsLambda: same pattern as TestCaseVfs in test_vfs_commands.cc but
// local to this translation unit to avoid ODR issues with the anonymous-
// namespace class there.
// ---------------------------------------------------------------------------
class TestCaseVfsLambda : public TestCaseBase<bool>
{
public:
    using Func = std::function<bool( VfsFixture & )>;

private:
    Func func;

public:
    TestCaseVfsLambda( const std::string & name_, Func func_,
                       bool expected_result_ = true )
    : TestCaseBase<bool>( name_, expected_result_ ),
      func( func_ )
    {}

    bool run() override
    {
        VfsFixture fix( name );
        return func( fix );
    }
};

// ---------------------------------------------------------------------------
// Constants mirroring IniKeys from Measurement_Result_Database_v3.hpp
// (exact string values copied from the header)
// ---------------------------------------------------------------------------
static constexpr const char* SEC_DICT   = "dict";
static constexpr const char* SEC_CFG    = "cfg";
static constexpr const char* SEC_RESULT = "result";

// [dict]
static constexpr const char* K_STATUS   = "status";
static constexpr const char* K_ID       = "id";
static constexpr const char* K_NAME     = "name";
static constexpr const char* K_TIME     = "time";
static constexpr const char* K_EXPORTED = "exported";

// [cfg] — all 49 fields written by write_entry()
static constexpr const char* K_GUID               = "guid";
static constexpr const char* K_TARGET_TEMPERATURE = "target_temperature";
static constexpr const char* K_TRG_SI_VISC        = "trg_si_visc";
static constexpr const char* K_TRG_SI_DENS        = "trg_si_dens";
static constexpr const char* K_DET_POLICY         = "det_policy";
static constexpr const char* K_MAX_N_DETS         = "max_n_dets";
static constexpr const char* K_D445_COR           = "d445_cor";
static constexpr const char* K_TARGET_RDV         = "target_rdv";
static constexpr const char* K_FILLING_MODE       = "filling_mode";
static constexpr const char* K_DRAIN_TIME         = "drain_time";
static constexpr const char* K_SOAK_TIME          = "soak_time";
static constexpr const char* K_DRY_TIME           = "dry_time";
static constexpr const char* K_EQUILIBRATION_TIME = "equilibration_time";
static constexpr const char* K_PREWETTING_TIME    = "prewetting_time";
static constexpr const char* K_MEAS_TIMEOUT       = "meas_timeout";
static constexpr const char* K_N_CLEAN_REPS       = "n_clean_reps";
static constexpr const char* K_FILL_THRESHOLD     = "fill_threshold";
static constexpr const char* K_COMMODITY_GROUP    = "commodity_group";
static constexpr const char* K_COMMODITY_ALPHA    = "commodity_alpha";
static constexpr const char* K_BOARD_SN           = "board_sn";
static constexpr const char* K_ASSEMBLY_SN        = "assembly_sn";
static constexpr const char* K_SW_VERSION         = "sw_version";
static constexpr const char* K_FW_VERSION         = "fw_version";
static constexpr const char* K_DEVICE_TYPE        = "device_type";
static constexpr const char* K_MEAS_MODULE_SN     = "meas_module_sn";
static constexpr const char* K_MEAS_MODULE_HW     = "meas_module_hw";
static constexpr const char* K_HW_VERSION         = "hw_version";
static constexpr const char* K_MEAS_MODE          = "meas_mode";
static constexpr const char* K_TEMP_ADJ_R0        = "temp_adj_r0";
static constexpr const char* K_TEMP_ADJ_A         = "temp_adj_a";
static constexpr const char* K_TEMP_ADJ_B         = "temp_adj_b";
static constexpr const char* K_TEMP_ADJ_C         = "temp_adj_c";
static constexpr const char* K_DENS_ADJ_A         = "dens_adj_a";
static constexpr const char* K_DENS_ADJ_AT        = "dens_adj_at";
static constexpr const char* K_DENS_ADJ_AT2       = "dens_adj_at2";
static constexpr const char* K_DENS_ADJ_B         = "dens_adj_b";
static constexpr const char* K_DENS_ADJ_BT        = "dens_adj_bt";
static constexpr const char* K_DENS_ADJ_BT2       = "dens_adj_bt2";
static constexpr const char* K_VISC_ADJ_A         = "visc_adj_a";
static constexpr const char* K_VISC_ADJ_AT        = "visc_adj_at";
static constexpr const char* K_VISC_ADJ_AT2       = "visc_adj_at2";
static constexpr const char* K_VISC_ADJ_B         = "visc_adj_b";
static constexpr const char* K_VISC_ADJ_BT        = "visc_adj_bt";
static constexpr const char* K_VISC_ADJ_BT2       = "visc_adj_bt2";
static constexpr const char* K_VISC_ADJ_C         = "visc_adj_c";
static constexpr const char* K_VISC_ADJ_CT        = "visc_adj_ct";
static constexpr const char* K_VISC_ADJ_CT2       = "visc_adj_ct2";
static constexpr const char* K_GAIN_ADJ           = "gain_adj";
static constexpr const char* K_AIR_ADJ            = "air_adj";

// [result] — all fields written by write_entry()
static constexpr const char* K_RES_STATUS       = "res_status";
static constexpr const char* K_RES_ABORT        = "res_abort";
static constexpr const char* K_RES_TIME         = "res_time";
static constexpr const char* K_RES_TEMP         = "res_temp";
static constexpr const char* K_RES_DENS         = "res_dens";
static constexpr const char* K_RES_VISC         = "res_visc";
static constexpr const char* K_RES_STAB         = "res_stab";
static constexpr const char* K_RES_FILL         = "res_fill";
static constexpr const char* K_D445_TEMP        = "d445_temp";
static constexpr const char* K_D445_DENS        = "d445_dens";
static constexpr const char* K_D445_VISC        = "d445_visc";
static constexpr const char* K_D445_STAB        = "d445_stab";
static constexpr const char* K_D445_FILL        = "d445_fill";
static constexpr const char* K_RDV              = "rdv";
static constexpr const char* K_RDD              = "rdd";
static constexpr const char* K_N_SUB_DETS       = "n_sub_dets";
static constexpr const char* K_GUID_TEMP_CAL    = "guid_temp_cal";
static constexpr const char* K_GUID_DENS_CAL    = "guid_dens_cal";
static constexpr const char* K_GUID_VISCO_CAL_0 = "guid_visco_cal_0";
static constexpr const char* K_GUID_VISCO_CAL_1 = "guid_visco_cal_1";
static constexpr const char* K_GUID_VISCO_CAL_2 = "guid_visco_cal_2";
// sub_N_* keys are generated dynamically (same as in write_entry loop)

// Path helper matching Measurement_Result_Database_v3::make_path()
std::string make_meas_path( uint32_t slot )
{
    return Tools::format( "/b/measurements/%04u.ini", slot );
}

// Buffer size used by write_entry() (Model::get_32_MBit_Flash_Page_Size()*4)
// On the real device that is 512*4 = 2048 bytes; use the same value here.
constexpr std::size_t FILE_BUFFER_SIZE = 528;

// ---------------------------------------------------------------------------
// write_entry_to_vfs: replicates ALL writes done by write_entry() for one slot.
//   Covers [dict] (5), [cfg] (49), [result] (21 + 12*3 sub-dets).
//   Returns true on success.
// ---------------------------------------------------------------------------
bool write_entry_to_vfs( SimpleFlashFs::Vfs::VfsServerInterface & vfs,
                         uint32_t                                   slot )
{
    const std::string path = make_meas_path( slot );

    // Replicate: delete any existing file first
    {
        auto fh = vfs.open( path, std::ios::in );
        if( fh ) {
            fh->delete_file();
        }
    }

    auto fh = vfs.open( path, std::ios::out );
    if( !fh ) {
        CPPDEBUG( Tools::format( "write_entry_to_vfs: cannot create %s", path ) );
        return false;
    }

    std::vector<std::byte>   raw_buf( FILE_BUFFER_SIZE );
    std::span<std::byte>     sbuf( raw_buf );
    SimpleFlashFs::FileBuffer        fb( *fh, sbuf );
    SimpleFlashFs::SimpleIni<1024>   ini( fb );

    // ── [dict] ────────────────────────────────────────────────────────────
    ini.write( SEC_DICT, K_STATUS,   uint32_t(1) );   // 1 = "in use"
    ini.write( SEC_DICT, K_ID,       uint64_t(42) );
    ini.write( SEC_DICT, K_NAME,     std::string_view("TestSample") );
    ini.write( SEC_DICT, K_TIME,     uint64_t(1718000000ULL) );
    ini.write( SEC_DICT, K_EXPORTED, uint32_t(0) );

    // ── [cfg] — all 49 fields ─────────────────────────────────────────────
    ini.write( SEC_CFG, K_GUID,               std::string_view("AABBCCDD-1234-5678-ABCD-001122334455") );
    ini.write( SEC_CFG, K_TARGET_TEMPERATURE, double(40.0) );
    ini.write( SEC_CFG, K_TRG_SI_VISC,        uint32_t(5) );
    ini.write( SEC_CFG, K_TRG_SI_DENS,        uint32_t(3) );
    ini.write( SEC_CFG, K_DET_POLICY,         uint32_t(0) );
    ini.write( SEC_CFG, K_MAX_N_DETS,         uint32_t(3) );
    ini.write( SEC_CFG, K_D445_COR,           uint32_t(1) );
    ini.write( SEC_CFG, K_TARGET_RDV,         double(0.05) );
    ini.write( SEC_CFG, K_FILLING_MODE,       uint32_t(0) );
    ini.write( SEC_CFG, K_DRAIN_TIME,         uint64_t(30000ULL) );
    ini.write( SEC_CFG, K_SOAK_TIME,          uint64_t(60000ULL) );
    ini.write( SEC_CFG, K_DRY_TIME,           uint64_t(120000ULL) );
    ini.write( SEC_CFG, K_EQUILIBRATION_TIME, uint64_t(300000ULL) );
    ini.write( SEC_CFG, K_PREWETTING_TIME,    uint64_t(10000ULL) );
    ini.write( SEC_CFG, K_MEAS_TIMEOUT,       uint64_t(600000ULL) );
    ini.write( SEC_CFG, K_N_CLEAN_REPS,       uint32_t(2) );
    ini.write( SEC_CFG, K_FILL_THRESHOLD,     double(0.8) );
    ini.write( SEC_CFG, K_COMMODITY_GROUP,    uint32_t(1) );
    ini.write( SEC_CFG, K_COMMODITY_ALPHA,    double(0.00065) );
    ini.write( SEC_CFG, K_BOARD_SN,           uint32_t(12345) );
    ini.write( SEC_CFG, K_ASSEMBLY_SN,        uint32_t(67890) );
    ini.write( SEC_CFG, K_SW_VERSION,         std::string_view("1.2.3.4") );
    ini.write( SEC_CFG, K_FW_VERSION,         std::string_view("0.9.1") );
    ini.write( SEC_CFG, K_DEVICE_TYPE,        std::string_view("SVM1001") );
    ini.write( SEC_CFG, K_MEAS_MODULE_SN,     uint32_t(11111) );
    ini.write( SEC_CFG, K_MEAS_MODULE_HW,     uint32_t(2) );
    ini.write( SEC_CFG, K_HW_VERSION,         uint32_t(3) );
    ini.write( SEC_CFG, K_MEAS_MODE,          uint32_t(2) );
    ini.write( SEC_CFG, K_TEMP_ADJ_R0,        double(100.0) );
    ini.write( SEC_CFG, K_TEMP_ADJ_A,         double(3.9083e-3) );
    ini.write( SEC_CFG, K_TEMP_ADJ_B,         double(-5.775e-7) );
    ini.write( SEC_CFG, K_TEMP_ADJ_C,         double(0.0) );
    ini.write( SEC_CFG, K_DENS_ADJ_A,         double(1.0) );
    ini.write( SEC_CFG, K_DENS_ADJ_AT,        double(0.0) );
    ini.write( SEC_CFG, K_DENS_ADJ_AT2,       double(0.0) );
    ini.write( SEC_CFG, K_DENS_ADJ_B,         double(0.0) );
    ini.write( SEC_CFG, K_DENS_ADJ_BT,        double(0.0) );
    ini.write( SEC_CFG, K_DENS_ADJ_BT2,       double(0.0) );
    ini.write( SEC_CFG, K_VISC_ADJ_A,         double(1.0) );
    ini.write( SEC_CFG, K_VISC_ADJ_AT,        double(0.0) );
    ini.write( SEC_CFG, K_VISC_ADJ_AT2,       double(0.0) );
    ini.write( SEC_CFG, K_VISC_ADJ_B,         double(0.0) );
    ini.write( SEC_CFG, K_VISC_ADJ_BT,        double(0.0) );
    ini.write( SEC_CFG, K_VISC_ADJ_BT2,       double(0.0) );
    ini.write( SEC_CFG, K_VISC_ADJ_C,         double(0.0) );
    ini.write( SEC_CFG, K_VISC_ADJ_CT,        double(0.0) );
    ini.write( SEC_CFG, K_VISC_ADJ_CT2,       double(0.0) );
    ini.write( SEC_CFG, K_GAIN_ADJ,           uint32_t(1000) );
    ini.write( SEC_CFG, K_AIR_ADJ,            double(-0.001) );

    // ── [result] — all fields ─────────────────────────────────────────────
    ini.write( SEC_RESULT, K_RES_STATUS,  uint32_t(2) );    // 2 = finished OK
    ini.write( SEC_RESULT, K_RES_ABORT,   int32_t(-1) );    // no abort
    ini.write( SEC_RESULT, K_RES_TIME,    uint64_t(1718001000ULL) );
    ini.write( SEC_RESULT, K_RES_TEMP,    float(40.01f) );
    ini.write( SEC_RESULT, K_RES_DENS,    float(850.123f) );
    ini.write( SEC_RESULT, K_RES_VISC,    float(5.678f) );
    ini.write( SEC_RESULT, K_RES_STAB,    uint32_t(4) );
    ini.write( SEC_RESULT, K_RES_FILL,    float(0.95f) );
    ini.write( SEC_RESULT, K_D445_TEMP,   float(40.02f) );
    ini.write( SEC_RESULT, K_D445_DENS,   float(851.0f) );
    ini.write( SEC_RESULT, K_D445_VISC,   float(5.7f) );
    ini.write( SEC_RESULT, K_D445_STAB,   uint32_t(3) );
    ini.write( SEC_RESULT, K_D445_FILL,   float(0.94f) );
    ini.write( SEC_RESULT, K_RDV,         double(0.001) );
    ini.write( SEC_RESULT, K_RDD,         double(0.0005) );
    ini.write( SEC_RESULT, K_N_SUB_DETS,  uint32_t(3) );
    ini.write( SEC_RESULT, K_GUID_TEMP_CAL,    std::string_view("TCAL-0001") );
    ini.write( SEC_RESULT, K_GUID_DENS_CAL,    std::string_view("DCAL-0002") );
    ini.write( SEC_RESULT, K_GUID_VISCO_CAL_0, std::string_view("VCAL-0003") );
    ini.write( SEC_RESULT, K_GUID_VISCO_CAL_1, std::string_view("VCAL-0004") );
    ini.write( SEC_RESULT, K_GUID_VISCO_CAL_2, std::string_view("VCAL-0005") );

    // Sub-determination records — all 12 fields per sub-det
    for( uint32_t n = 0; n < 3; ++n ) {
        const std::string pfx = Tools::format( "sub_%u_", n );
        ini.write( SEC_RESULT, (pfx + "status").c_str(),   uint32_t(2) );
        ini.write( SEC_RESULT, (pfx + "abort").c_str(),    int32_t(-1) );
        ini.write( SEC_RESULT, (pfx + "pre_temp").c_str(), float(40.0f  + n * 0.01f) );
        ini.write( SEC_RESULT, (pfx + "pre_dens").c_str(), float(850.0f + n * 0.1f) );
        ini.write( SEC_RESULT, (pfx + "pre_visc").c_str(), float(5.6f   + n * 0.01f) );
        ini.write( SEC_RESULT, (pfx + "pre_stab").c_str(), uint32_t(n + 1) );
        ini.write( SEC_RESULT, (pfx + "pre_fill").c_str(), float(0.92f  + n * 0.01f) );
        ini.write( SEC_RESULT, (pfx + "cor_temp").c_str(), float(40.0f  + n * 0.01f) );
        ini.write( SEC_RESULT, (pfx + "cor_dens").c_str(), float(850.1f + n * 0.1f) );
        ini.write( SEC_RESULT, (pfx + "cor_visc").c_str(), float(5.65f  + n * 0.01f) );
        ini.write( SEC_RESULT, (pfx + "cor_stab").c_str(), uint32_t(n + 1) );
        ini.write( SEC_RESULT, (pfx + "cor_fill").c_str(), float(0.93f  + n * 0.01f) );
    }

    if( !fb.flush() ) {
        CPPDEBUG( Tools::format( "write_entry_to_vfs: flush failed for slot %u (VFS full?)", slot ) );
        return false;
    }
    return true;
}

// ---------------------------------------------------------------------------
// read_entry_from_vfs: reads the INI back and verifies ALL key/value pairs
//   written by write_entry_to_vfs() above.  Returns true if all match.
// ---------------------------------------------------------------------------
bool read_entry_from_vfs( SimpleFlashFs::Vfs::VfsServerInterface & vfs,
                          uint32_t                                   slot )
{
    const std::string path = make_meas_path( slot );

    auto fh = vfs.open( path, std::ios::in );
    if( !fh ) {
        CPPDEBUG( Tools::format( "read_entry_from_vfs: cannot open %s", path ) );
        return false;
    }

    std::vector<std::byte>   raw_buf( FILE_BUFFER_SIZE );
    std::span<std::byte>     sbuf( raw_buf );
    SimpleFlashFs::FileBuffer        fb( *fh, sbuf );
    SimpleFlashFs::SimpleIni<1024>   ini( fb );

    // ── [dict] ────────────────────────────────────────────────────────────
    {
        uint32_t status = 0;
        if( !ini.read( SEC_DICT, K_STATUS, status ) || status != 1 ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: dict/status mismatch (got %u)", status ) );
            return false;
        }

        uint64_t id = 0;
        if( !ini.read( SEC_DICT, K_ID, id ) || id != 42 ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: dict/id mismatch (got %llu)", (unsigned long long)id ) );
            return false;
        }

        std::string_view name;
        if( !ini.read( SEC_DICT, K_NAME, name ) || name != "TestSample" ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: dict/name mismatch (got '%s')", std::string(name) ) );
            return false;
        }

        uint64_t time_val = 0;
        if( !ini.read( SEC_DICT, K_TIME, time_val ) || time_val != 1718000000ULL ) {
            CPPDEBUG( "read_entry_from_vfs: dict/time mismatch" );
            return false;
        }

        uint32_t exported = 99;
        if( !ini.read( SEC_DICT, K_EXPORTED, exported ) || exported != 0 ) {
            CPPDEBUG( "read_entry_from_vfs: dict/exported mismatch" );
            return false;
        }
    }

    // ── [cfg] — all 49 fields ─────────────────────────────────────────────
    {
        std::string_view guid;
        if( !ini.read( SEC_CFG, K_GUID, guid ) ||
            guid != "AABBCCDD-1234-5678-ABCD-001122334455" ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: cfg/guid mismatch (got '%s')", std::string(guid) ) );
            return false;
        }

        double target_temp = 0.0;
        if( !ini.read( SEC_CFG, K_TARGET_TEMPERATURE, target_temp ) || target_temp != 40.0 ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/target_temperature mismatch" );
            return false;
        }

        uint32_t trg_si_visc = 0;
        if( !ini.read( SEC_CFG, K_TRG_SI_VISC, trg_si_visc ) || trg_si_visc != 5 ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: cfg/trg_si_visc mismatch (got %u)", trg_si_visc ) );
            return false;
        }

        uint32_t trg_si_dens = 0;
        if( !ini.read( SEC_CFG, K_TRG_SI_DENS, trg_si_dens ) || trg_si_dens != 3 ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: cfg/trg_si_dens mismatch (got %u)", trg_si_dens ) );
            return false;
        }

        uint32_t det_policy = 99;
        if( !ini.read( SEC_CFG, K_DET_POLICY, det_policy ) || det_policy != 0 ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: cfg/det_policy mismatch (got %u)", det_policy ) );
            return false;
        }

        uint32_t max_n_dets = 0;
        if( !ini.read( SEC_CFG, K_MAX_N_DETS, max_n_dets ) || max_n_dets != 3 ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: cfg/max_n_dets mismatch (got %u)", max_n_dets ) );
            return false;
        }

        uint32_t d445_cor = 0;
        if( !ini.read( SEC_CFG, K_D445_COR, d445_cor ) || d445_cor != 1 ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/d445_cor mismatch" );
            return false;
        }

        double target_rdv = 0.0;
        if( !ini.read( SEC_CFG, K_TARGET_RDV, target_rdv ) ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/target_rdv missing" );
            return false;
        }

        uint32_t filling_mode = 99;
        if( !ini.read( SEC_CFG, K_FILLING_MODE, filling_mode ) || filling_mode != 0 ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/filling_mode mismatch" );
            return false;
        }

        uint64_t drain_time = 0;
        if( !ini.read( SEC_CFG, K_DRAIN_TIME, drain_time ) || drain_time != 30000ULL ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/drain_time mismatch" );
            return false;
        }

        uint64_t soak_time = 0;
        if( !ini.read( SEC_CFG, K_SOAK_TIME, soak_time ) || soak_time != 60000ULL ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/soak_time mismatch" );
            return false;
        }

        uint64_t dry_time = 0;
        if( !ini.read( SEC_CFG, K_DRY_TIME, dry_time ) || dry_time != 120000ULL ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/dry_time mismatch" );
            return false;
        }

        uint64_t equil_time = 0;
        if( !ini.read( SEC_CFG, K_EQUILIBRATION_TIME, equil_time ) || equil_time != 300000ULL ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/equilibration_time mismatch" );
            return false;
        }

        uint64_t prewet_time = 0;
        if( !ini.read( SEC_CFG, K_PREWETTING_TIME, prewet_time ) || prewet_time != 10000ULL ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/prewetting_time mismatch" );
            return false;
        }

        uint64_t meas_timeout = 0;
        if( !ini.read( SEC_CFG, K_MEAS_TIMEOUT, meas_timeout ) || meas_timeout != 600000ULL ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/meas_timeout mismatch" );
            return false;
        }

        uint32_t n_clean_reps = 0;
        if( !ini.read( SEC_CFG, K_N_CLEAN_REPS, n_clean_reps ) || n_clean_reps != 2 ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/n_clean_reps mismatch" );
            return false;
        }

        double fill_threshold = 0.0;
        if( !ini.read( SEC_CFG, K_FILL_THRESHOLD, fill_threshold ) ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/fill_threshold missing" );
            return false;
        }

        uint32_t commodity_group = 99;
        if( !ini.read( SEC_CFG, K_COMMODITY_GROUP, commodity_group ) || commodity_group != 1 ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/commodity_group mismatch" );
            return false;
        }

        double commodity_alpha = 0.0;
        if( !ini.read( SEC_CFG, K_COMMODITY_ALPHA, commodity_alpha ) ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/commodity_alpha missing" );
            return false;
        }

        uint32_t board_sn = 0;
        if( !ini.read( SEC_CFG, K_BOARD_SN, board_sn ) || board_sn != 12345 ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: cfg/board_sn mismatch (got %u)", board_sn ) );
            return false;
        }

        uint32_t assembly_sn = 0;
        if( !ini.read( SEC_CFG, K_ASSEMBLY_SN, assembly_sn ) || assembly_sn != 67890 ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: cfg/assembly_sn mismatch (got %u)", assembly_sn ) );
            return false;
        }

        std::string_view sw_ver;
        if( !ini.read( SEC_CFG, K_SW_VERSION, sw_ver ) || sw_ver != "1.2.3.4" ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: cfg/sw_version mismatch (got '%s')", std::string(sw_ver) ) );
            return false;
        }

        std::string_view fw_ver;
        if( !ini.read( SEC_CFG, K_FW_VERSION, fw_ver ) || fw_ver != "0.9.1" ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: cfg/fw_version mismatch (got '%s')", std::string(fw_ver) ) );
            return false;
        }

        std::string_view device_type;
        if( !ini.read( SEC_CFG, K_DEVICE_TYPE, device_type ) || device_type != "SVM1001" ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: cfg/device_type mismatch (got '%s')", std::string(device_type) ) );
            return false;
        }

        uint32_t meas_module_sn = 0;
        if( !ini.read( SEC_CFG, K_MEAS_MODULE_SN, meas_module_sn ) || meas_module_sn != 11111 ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/meas_module_sn mismatch" );
            return false;
        }

        uint32_t meas_module_hw = 0;
        if( !ini.read( SEC_CFG, K_MEAS_MODULE_HW, meas_module_hw ) || meas_module_hw != 2 ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/meas_module_hw mismatch" );
            return false;
        }

        uint32_t hw_version = 0;
        if( !ini.read( SEC_CFG, K_HW_VERSION, hw_version ) || hw_version != 3 ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/hw_version mismatch" );
            return false;
        }

        uint32_t meas_mode = 0;
        if( !ini.read( SEC_CFG, K_MEAS_MODE, meas_mode ) || meas_mode != 2 ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/meas_mode mismatch" );
            return false;
        }

        // Calibration adjustment fields — verify they are present and readable
        double adj = 0.0;
        if( !ini.read( SEC_CFG, K_TEMP_ADJ_R0,  adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/temp_adj_r0 missing" ); return false; }
        if( !ini.read( SEC_CFG, K_TEMP_ADJ_A,   adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/temp_adj_a missing" ); return false; }
        if( !ini.read( SEC_CFG, K_TEMP_ADJ_B,   adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/temp_adj_b missing" ); return false; }
        if( !ini.read( SEC_CFG, K_TEMP_ADJ_C,   adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/temp_adj_c missing" ); return false; }
        if( !ini.read( SEC_CFG, K_DENS_ADJ_A,   adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/dens_adj_a missing" ); return false; }
        if( !ini.read( SEC_CFG, K_DENS_ADJ_AT,  adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/dens_adj_at missing" ); return false; }
        if( !ini.read( SEC_CFG, K_DENS_ADJ_AT2, adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/dens_adj_at2 missing" ); return false; }
        if( !ini.read( SEC_CFG, K_DENS_ADJ_B,   adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/dens_adj_b missing" ); return false; }
        if( !ini.read( SEC_CFG, K_DENS_ADJ_BT,  adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/dens_adj_bt missing" ); return false; }
        if( !ini.read( SEC_CFG, K_DENS_ADJ_BT2, adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/dens_adj_bt2 missing" ); return false; }
        if( !ini.read( SEC_CFG, K_VISC_ADJ_A,   adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/visc_adj_a missing" ); return false; }
        if( !ini.read( SEC_CFG, K_VISC_ADJ_AT,  adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/visc_adj_at missing" ); return false; }
        if( !ini.read( SEC_CFG, K_VISC_ADJ_AT2, adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/visc_adj_at2 missing" ); return false; }
        if( !ini.read( SEC_CFG, K_VISC_ADJ_B,   adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/visc_adj_b missing" ); return false; }
        if( !ini.read( SEC_CFG, K_VISC_ADJ_BT,  adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/visc_adj_bt missing" ); return false; }
        if( !ini.read( SEC_CFG, K_VISC_ADJ_BT2, adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/visc_adj_bt2 missing" ); return false; }
        if( !ini.read( SEC_CFG, K_VISC_ADJ_C,   adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/visc_adj_c missing" ); return false; }
        if( !ini.read( SEC_CFG, K_VISC_ADJ_CT,  adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/visc_adj_ct missing" ); return false; }
        if( !ini.read( SEC_CFG, K_VISC_ADJ_CT2, adj ) ) { CPPDEBUG( "read_entry_from_vfs: cfg/visc_adj_ct2 missing" ); return false; }

        uint32_t gain_adj = 0;
        if( !ini.read( SEC_CFG, K_GAIN_ADJ, gain_adj ) || gain_adj != 1000 ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/gain_adj mismatch" );
            return false;
        }

        double air_adj = 0.0;
        if( !ini.read( SEC_CFG, K_AIR_ADJ, air_adj ) ) {
            CPPDEBUG( "read_entry_from_vfs: cfg/air_adj missing" );
            return false;
        }
    }

    // ── [result] — all fields ─────────────────────────────────────────────
    {
        uint32_t res_status = 0;
        if( !ini.read( SEC_RESULT, K_RES_STATUS, res_status ) || res_status != 2 ) {
            CPPDEBUG( "read_entry_from_vfs: result/res_status mismatch" );
            return false;
        }

        int32_t res_abort = 0;
        if( !ini.read( SEC_RESULT, K_RES_ABORT, res_abort ) || res_abort != -1 ) {
            CPPDEBUG( "read_entry_from_vfs: result/res_abort mismatch" );
            return false;
        }

        uint64_t res_time = 0;
        if( !ini.read( SEC_RESULT, K_RES_TIME, res_time ) || res_time != 1718001000ULL ) {
            CPPDEBUG( "read_entry_from_vfs: result/res_time mismatch" );
            return false;
        }

        float res_temp = 0.0f;
        if( !ini.read( SEC_RESULT, K_RES_TEMP, res_temp ) ) {
            CPPDEBUG( "read_entry_from_vfs: result/res_temp missing" );
            return false;
        }

        float res_dens = 0.0f;
        if( !ini.read( SEC_RESULT, K_RES_DENS, res_dens ) ) {
            CPPDEBUG( "read_entry_from_vfs: result/res_dens missing" );
            return false;
        }

        float res_visc = 0.0f;
        if( !ini.read( SEC_RESULT, K_RES_VISC, res_visc ) ) {
            CPPDEBUG( "read_entry_from_vfs: result/res_visc missing" );
            return false;
        }

        uint32_t res_stab = 0;
        if( !ini.read( SEC_RESULT, K_RES_STAB, res_stab ) || res_stab != 4 ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: result/res_stab mismatch (got %u)", res_stab ) );
            return false;
        }

        float res_fill = 0.0f;
        if( !ini.read( SEC_RESULT, K_RES_FILL, res_fill ) ) {
            CPPDEBUG( "read_entry_from_vfs: result/res_fill missing" );
            return false;
        }

        float d445_temp = 0.0f;
        if( !ini.read( SEC_RESULT, K_D445_TEMP, d445_temp ) ) {
            CPPDEBUG( "read_entry_from_vfs: result/d445_temp missing" );
            return false;
        }

        float d445_dens = 0.0f;
        if( !ini.read( SEC_RESULT, K_D445_DENS, d445_dens ) ) {
            CPPDEBUG( "read_entry_from_vfs: result/d445_dens missing" );
            return false;
        }

        float d445_visc = 0.0f;
        if( !ini.read( SEC_RESULT, K_D445_VISC, d445_visc ) ) {
            CPPDEBUG( "read_entry_from_vfs: result/d445_visc missing" );
            return false;
        }

        uint32_t d445_stab = 0;
        if( !ini.read( SEC_RESULT, K_D445_STAB, d445_stab ) || d445_stab != 3 ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: result/d445_stab mismatch (got %u)", d445_stab ) );
            return false;
        }

        float d445_fill = 0.0f;
        if( !ini.read( SEC_RESULT, K_D445_FILL, d445_fill ) ) {
            CPPDEBUG( "read_entry_from_vfs: result/d445_fill missing" );
            return false;
        }

        double rdv = 0.0;
        if( !ini.read( SEC_RESULT, K_RDV, rdv ) ) {
            CPPDEBUG( "read_entry_from_vfs: result/rdv missing" );
            return false;
        }

        double rdd = 0.0;
        if( !ini.read( SEC_RESULT, K_RDD, rdd ) ) {
            CPPDEBUG( "read_entry_from_vfs: result/rdd missing" );
            return false;
        }

        uint32_t n_sub = 0;
        if( !ini.read( SEC_RESULT, K_N_SUB_DETS, n_sub ) || n_sub != 3 ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: result/n_sub_dets mismatch (got %u)", n_sub ) );
            return false;
        }

        std::string_view guid_tc;
        if( !ini.read( SEC_RESULT, K_GUID_TEMP_CAL, guid_tc ) || guid_tc != "TCAL-0001" ) {
            CPPDEBUG( "read_entry_from_vfs: result/guid_temp_cal mismatch" );
            return false;
        }

        std::string_view guid_dc;
        if( !ini.read( SEC_RESULT, K_GUID_DENS_CAL, guid_dc ) || guid_dc != "DCAL-0002" ) {
            CPPDEBUG( "read_entry_from_vfs: result/guid_dens_cal mismatch" );
            return false;
        }

        std::string_view guid_vc0;
        if( !ini.read( SEC_RESULT, K_GUID_VISCO_CAL_0, guid_vc0 ) || guid_vc0 != "VCAL-0003" ) {
            CPPDEBUG( "read_entry_from_vfs: result/guid_visco_cal_0 mismatch" );
            return false;
        }

        std::string_view guid_vc1;
        if( !ini.read( SEC_RESULT, K_GUID_VISCO_CAL_1, guid_vc1 ) || guid_vc1 != "VCAL-0004" ) {
            CPPDEBUG( "read_entry_from_vfs: result/guid_visco_cal_1 mismatch" );
            return false;
        }

        std::string_view guid_vc2;
        if( !ini.read( SEC_RESULT, K_GUID_VISCO_CAL_2, guid_vc2 ) || guid_vc2 != "VCAL-0005" ) {
            CPPDEBUG( "read_entry_from_vfs: result/guid_visco_cal_2 mismatch" );
            return false;
        }
    }

    // ── sub-determinations — all 12 fields per sub-det ────────────────────
    for( uint32_t n = 0; n < 3; ++n ) {
        const std::string pfx = Tools::format( "sub_%u_", n );

        uint32_t sub_status = 0;
        if( !ini.read( SEC_RESULT, (pfx + "status").c_str(), sub_status ) || sub_status != 2 ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: sub_%u_status mismatch", n ) );
            return false;
        }

        int32_t sub_abort = 0;
        if( !ini.read( SEC_RESULT, (pfx + "abort").c_str(), sub_abort ) || sub_abort != -1 ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: sub_%u_abort mismatch", n ) );
            return false;
        }

        float pre_temp = 0.0f;
        if( !ini.read( SEC_RESULT, (pfx + "pre_temp").c_str(), pre_temp ) ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: sub_%u_pre_temp missing", n ) );
            return false;
        }

        float pre_dens = 0.0f;
        if( !ini.read( SEC_RESULT, (pfx + "pre_dens").c_str(), pre_dens ) ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: sub_%u_pre_dens missing", n ) );
            return false;
        }

        float pre_visc = 0.0f;
        if( !ini.read( SEC_RESULT, (pfx + "pre_visc").c_str(), pre_visc ) ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: sub_%u_pre_visc missing", n ) );
            return false;
        }

        uint32_t pre_stab = 0;
        if( !ini.read( SEC_RESULT, (pfx + "pre_stab").c_str(), pre_stab ) || pre_stab != n + 1 ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: sub_%u_pre_stab mismatch (got %u)", n, pre_stab ) );
            return false;
        }

        float pre_fill = 0.0f;
        if( !ini.read( SEC_RESULT, (pfx + "pre_fill").c_str(), pre_fill ) ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: sub_%u_pre_fill missing", n ) );
            return false;
        }

        float cor_temp = 0.0f;
        if( !ini.read( SEC_RESULT, (pfx + "cor_temp").c_str(), cor_temp ) ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: sub_%u_cor_temp missing", n ) );
            return false;
        }

        float cor_dens = 0.0f;
        if( !ini.read( SEC_RESULT, (pfx + "cor_dens").c_str(), cor_dens ) ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: sub_%u_cor_dens missing", n ) );
            return false;
        }

        float cor_visc = 0.0f;
        if( !ini.read( SEC_RESULT, (pfx + "cor_visc").c_str(), cor_visc ) ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: sub_%u_cor_visc missing", n ) );
            return false;
        }

        uint32_t cor_stab = 0;
        if( !ini.read( SEC_RESULT, (pfx + "cor_stab").c_str(), cor_stab ) || cor_stab != n + 1 ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: sub_%u_cor_stab mismatch (got %u)", n, cor_stab ) );
            return false;
        }

        float cor_fill = 0.0f;
        if( !ini.read( SEC_RESULT, (pfx + "cor_fill").c_str(), cor_fill ) ) {
            CPPDEBUG( Tools::format( "read_entry_from_vfs: sub_%u_cor_fill missing", n ) );
            return false;
        }
    }

    return true;
}

} // namespace
// AI generated by GitHub Copilot Claude Sonnet 4.6 END

// AI generated by GitHub Copilot Claude Sonnet 4.6 START
// ---------------------------------------------------------------------------
// test_case_mrdb_write_entry_basic
//
// Verifies the full write-then-read-back round trip for a single measurement
// slot, covering all three INI sections ([dict], [cfg], [result]) including
// per-sub-determination entries. Mirrors the happy-path of write_entry().
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_mrdb_write_entry_basic()
{
    return std::make_shared<TestCaseVfsLambda>( __FUNCTION__,
        []( VfsFixture & fix ) -> bool {
            if( !fix.run( "format a: ; format b: ;" ).all_ok ) {
                CPPDEBUG( "test_case_mrdb_write_entry_basic: format failed" );
                return false;
            }

            if( !write_entry_to_vfs( *fix.vfs, 1 ) ) {
                return false;
            }

            // Verify the file was created on drive b
            auto ib = inspect_drive( fix, "b", false );
            if( !ib.mounted ) {
                CPPDEBUG( "test_case_mrdb_write_entry_basic: drive b not mounted" );
                return false;
            }
            auto * f = find_file( ib, "measurements/0001.ini" );
            if( !f ) {
                CPPDEBUG( "test_case_mrdb_write_entry_basic: measurements/0001.ini not found" );
                return false;
            }
            if( f->file_len == 0 ) {
                CPPDEBUG( "test_case_mrdb_write_entry_basic: measurements/0001.ini is empty" );
                return false;
            }

            // Read back and verify values
            if( !read_entry_from_vfs( *fix.vfs, 1 ) ) {
                return false;
            }

            return true;
        } );
}

// ---------------------------------------------------------------------------
// test_case_mrdb_write_entry_overwrite
//
// Writes slot 1 with initial values, then overwrites it (replicating the
// delete-before-write pattern in write_entry()). Verifies that the old
// values are gone and the new values are correctly read back.
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_mrdb_write_entry_overwrite()
{
    return std::make_shared<TestCaseVfsLambda>( __FUNCTION__,
        []( VfsFixture & fix ) -> bool {
            if( !fix.run( "format a: ; format b: ;" ).all_ok ) {
                CPPDEBUG( "test_case_mrdb_write_entry_overwrite: format failed" );
                return false;
            }

            // First write
            if( !write_entry_to_vfs( *fix.vfs, 1 ) ) {
                return false;
            }

            // Second write to the same slot with different id (overwrite)
            const std::string path = make_meas_path( 1 );

            // Delete existing file (as write_entry() does)
            {
                auto fh = fix.vfs->open( path, std::ios::in );
                if( !fh ) {
                    CPPDEBUG( "test_case_mrdb_write_entry_overwrite: cannot open for delete" );
                    return false;
                }
                fh->delete_file();
            }

            // Write new content
            {
                auto fh2 = fix.vfs->open( path, std::ios::out );
                if( !fh2 ) {
                    CPPDEBUG( "test_case_mrdb_write_entry_overwrite: cannot create for overwrite" );
                    return false;
                }

                std::vector<std::byte>   raw_buf( FILE_BUFFER_SIZE );
                std::span<std::byte>     sbuf( raw_buf );
                SimpleFlashFs::FileBuffer        fb( *fh2, sbuf );
                SimpleFlashFs::SimpleIni<1024>   ini( fb );

                ini.write( SEC_DICT, K_STATUS,   uint32_t(1) );
                ini.write( SEC_DICT, K_ID,       uint64_t(99) );   // new id
                ini.write( SEC_DICT, K_NAME,     std::string_view("Overwritten") );
                ini.write( SEC_DICT, K_TIME,     uint64_t(1718999999ULL) );
                ini.write( SEC_DICT, K_EXPORTED, uint32_t(0) );

                ini.write( SEC_CFG, K_GUID,               std::string_view("FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF") );
                ini.write( SEC_CFG, K_TARGET_TEMPERATURE, double(20.0) );
                ini.write( SEC_CFG, K_DET_POLICY,         uint32_t(1) );
                ini.write( SEC_CFG, K_MAX_N_DETS,         uint32_t(1) );
                ini.write( SEC_CFG, K_SW_VERSION,         std::string_view("2.0.0.0") );
                ini.write( SEC_CFG, K_MEAS_MODE,          uint32_t(0) );

                ini.write( SEC_RESULT, K_RES_STATUS, uint32_t(3) );
                ini.write( SEC_RESULT, K_RES_ABORT,  int32_t(0) );
                ini.write( SEC_RESULT, K_RES_TIME,   uint64_t(1718999000ULL) );
                ini.write( SEC_RESULT, K_RES_TEMP,   double(20.05) );
                ini.write( SEC_RESULT, K_RES_DENS,   double(900.0) );
                ini.write( SEC_RESULT, K_RES_VISC,   double(10.0) );
                ini.write( SEC_RESULT, K_N_SUB_DETS, uint32_t(1) );
                ini.write( SEC_RESULT, K_RDV,        double(0.002) );
                ini.write( SEC_RESULT, K_RDD,        double(0.001) );

                if( !fb.flush() ) {
                    CPPDEBUG( "test_case_mrdb_write_entry_overwrite: flush failed" );
                    return false;
                }
            }

            // Verify new values
            auto fh3 = fix.vfs->open( path, std::ios::in );
            if( !fh3 ) {
                CPPDEBUG( "test_case_mrdb_write_entry_overwrite: cannot open for read-back" );
                return false;
            }
            std::vector<std::byte>   raw_buf( FILE_BUFFER_SIZE );
            std::span<std::byte>     sbuf( raw_buf );
            SimpleFlashFs::FileBuffer        fb3( *fh3, sbuf );
            SimpleFlashFs::SimpleIni<1024>   ini3( fb3 );

            uint64_t id = 0;
            if( !ini3.read( SEC_DICT, K_ID, id ) || id != 99 ) {
                CPPDEBUG( Tools::format( "test_case_mrdb_write_entry_overwrite: id mismatch after overwrite (got %llu)", (unsigned long long)id ) );
                return false;
            }

            std::string_view name;
            if( !ini3.read( SEC_DICT, K_NAME, name ) || name != "Overwritten" ) {
                CPPDEBUG( "test_case_mrdb_write_entry_overwrite: name mismatch after overwrite" );
                return false;
            }

            uint32_t res_status = 0;
            if( !ini3.read( SEC_RESULT, K_RES_STATUS, res_status ) || res_status != 3 ) {
                CPPDEBUG( "test_case_mrdb_write_entry_overwrite: res_status mismatch after overwrite" );
                return false;
            }

            return true;
        } );
}

// ---------------------------------------------------------------------------
// test_case_mrdb_write_entry_multiple_slots
//
// Writes three different measurement slots and verifies that each can be
// read back independently, confirming that the slot-based path
// "/b/measurements/<NNNN>.ini" correctly separates entries.
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_mrdb_write_entry_multiple_slots()
{
    return std::make_shared<TestCaseVfsLambda>( __FUNCTION__,
        []( VfsFixture & fix ) -> bool {
            if( !fix.run( "format a: ; format b: ;" ).all_ok ) {
                CPPDEBUG( "test_case_mrdb_write_entry_multiple_slots: format failed" );
                return false;
            }

            // Write three different slots
            for( uint32_t slot : { 1u, 5u, 42u } ) {
                const std::string path = make_meas_path( slot );

                auto fh = fix.vfs->open( path, std::ios::out );
                if( !fh ) {
                    CPPDEBUG( Tools::format( "test_case_mrdb_write_entry_multiple_slots: cannot create slot %u", slot ) );
                    return false;
                }

                std::vector<std::byte>   raw_buf( FILE_BUFFER_SIZE );
                std::span<std::byte>     sbuf( raw_buf );
                SimpleFlashFs::FileBuffer        fb( *fh, sbuf );
                SimpleFlashFs::SimpleIni<1024>   ini( fb );

                ini.write( SEC_DICT, K_STATUS, uint32_t(1) );
                ini.write( SEC_DICT, K_ID,     uint64_t(slot * 100) );  // unique per slot
                ini.write( SEC_DICT, K_NAME,   std::string_view("SlotTest") );
                ini.write( SEC_DICT, K_TIME,   uint64_t(1718000000ULL + slot) );

                ini.write( SEC_CFG, K_GUID,               std::string_view("00000000-0000-0000-0000-000000000000") );
                ini.write( SEC_CFG, K_TARGET_TEMPERATURE, double(25.0) );
                ini.write( SEC_CFG, K_SW_VERSION,         std::string_view("3.0.0") );

                ini.write( SEC_RESULT, K_RES_STATUS, uint32_t(2) );
                ini.write( SEC_RESULT, K_RES_ABORT,  int32_t(-1) );
                ini.write( SEC_RESULT, K_N_SUB_DETS, uint32_t(1) );

                if( !fb.flush() ) {
                    CPPDEBUG( Tools::format( "test_case_mrdb_write_entry_multiple_slots: flush failed for slot %u", slot ) );
                    return false;
                }
            }

            // Read back each slot and verify its unique id
            for( uint32_t slot : { 1u, 5u, 42u } ) {
                const std::string path = make_meas_path( slot );

                auto fh = fix.vfs->open( path, std::ios::in );
                if( !fh ) {
                    CPPDEBUG( Tools::format( "test_case_mrdb_write_entry_multiple_slots: cannot open slot %u", slot ) );
                    return false;
                }

                std::vector<std::byte>   raw_buf( FILE_BUFFER_SIZE );
                std::span<std::byte>     sbuf( raw_buf );
                SimpleFlashFs::FileBuffer        fb( *fh, sbuf );
                SimpleFlashFs::SimpleIni<1024>   ini( fb );

                uint64_t id = 0;
                if( !ini.read( SEC_DICT, K_ID, id ) ) {
                    CPPDEBUG( Tools::format( "test_case_mrdb_write_entry_multiple_slots: slot %u id not readable", slot ) );
                    return false;
                }
                if( id != uint64_t(slot * 100) ) {
                    CPPDEBUG( Tools::format( "test_case_mrdb_write_entry_multiple_slots: slot %u id mismatch: got %llu, want %llu",
                              slot, (unsigned long long)id, (unsigned long long)(slot * 100) ) );
                    return false;
                }
            }

            // Inspect drive b - all three files should be present
            auto ib = inspect_drive( fix, "b", false );
            if( !ib.mounted ) {
                CPPDEBUG( "test_case_mrdb_write_entry_multiple_slots: drive b not mounted" );
                return false;
            }

            for( uint32_t slot : { 1u, 5u, 42u } ) {
                const std::string fname = Tools::format( "measurements/%04u.ini", slot );
                if( !find_file( ib, fname ) ) {
                    CPPDEBUG( Tools::format( "test_case_mrdb_write_entry_multiple_slots: %s not found on drive", fname ) );
                    return false;
                }
            }

            return true;
        } );
}
// AI generated by GitHub Copilot Claude Sonnet 4.6 END
