/*
 * test_vfs.cc
 *
 * Test runner for the two-drive VFS server. Mirrors the structure of
 * test_static.cc / test_2face.cc but works on top of the same
 * SimpleFlashFsThreadedVfsServer + FramFsImplDetail used by
 * two_drives_dynamic.
 *
 * AI generated by GitHub Copilot Claude Opus 4.7 START
 *  Created on: 12.06.2026
 * AI generated by GitHub Copilot Claude Opus 4.7 END
 */
#include "ColoredOutput.h"
#include "ColBuilder.h"
#include <arg.h>
#include <iostream>
#include <OutDebug.h>
#include <memory>
#include <format.h>
#include "test_vfs_commands.h"
#include "test_mrdb_write_entry.h"
#include "test_simple_ini_compact.h"
#include "test_file_name_cache.h"
#include <set>
#include <string_utils.h>
#include <SimOutDebug.h>
#include <chrono>

using namespace Tools;

// AI generated by GitHub Copilot Claude Opus 4.7 START
int main( int argc, char ** argv )
{
	ColoredOutput co;

	Arg::Arg arg( argc, argv );
	arg.addPrefix( "-" );
	arg.addPrefix( "--" );

	Arg::OptionChain oc_info;
	arg.addChainR( &oc_info );
	oc_info.setMinMatch( 1 );
	oc_info.setContinueOnMatch( false );
	oc_info.setContinueOnFail( true );

	Arg::FlagOption o_help( "help" );
	o_help.setDescription( "Show this page" );
	oc_info.addOptionR( &o_help );

	Arg::FlagOption o_debug( "d" );
	o_debug.addName( "debug" );
	o_debug.setDescription( "print debugging messages" );
	o_debug.setRequired( false );
	arg.addOptionR( &o_debug );

	Arg::IntOption o_testcase( "t" );
	o_testcase.addName( "testcase" );
	o_testcase.setDescription( "run testcase 1 2 ..." );
	o_testcase.setRequired( false );
	arg.addOptionR( &o_testcase );

	Arg::FlagOption o_list_tests( "l" );
    o_list_tests.addName( "list-tests" );
    o_list_tests.setDescription( "List all available tests" );
    arg.addOptionR( &o_list_tests );

	if( !arg.parse() ) {
		std::cout << arg.getHelp( 5, 20, 30, 80 ) << std::endl;
		return 1;
	}

	if( o_debug.getState() ) {		
		SimOutDebug::init();
	}

	if( o_help.getState() ) {
		std::cout << arg.getHelp( 5, 20, 30, 80 ) << std::endl;
		return 1;
	}

#if __cpp_exceptions > 0
	try {
#endif

		std::vector<std::shared_ptr<TestCaseBase<bool>>> test_cases;

		// One test per command; format() runs first so anything that
		// depends on a mounted fs has a clean slate.
		test_cases.push_back( test_case_vfs_format() );
		test_cases.push_back( test_case_vfs_pwd() );
		test_cases.push_back( test_case_vfs_cd() );
		test_cases.push_back( test_case_vfs_dos_change_drive() );
		test_cases.push_back( test_case_vfs_touch() );
		test_cases.push_back( test_case_vfs_ls_empty() );
		test_cases.push_back( test_case_vfs_ls_after_touch() );
		test_cases.push_back( test_case_vfs_dir_alias() );
		test_cases.push_back( test_case_vfs_test_count() );
		test_cases.push_back( test_case_vfs_cat() );
		test_cases.push_back( test_case_vfs_cp_same_drive() );
		test_cases.push_back( test_case_vfs_cp_cross_drive() );
		test_cases.push_back( test_case_vfs_mv_rename() );
		test_cases.push_back( test_case_vfs_rm() );
		test_cases.push_back( test_case_vfs_help() );
		test_cases.push_back( test_case_vfs_quit() );
		test_cases.push_back( test_case_vfs_cleanup() );
		test_cases.push_back( test_case_vfs_test1_full_flow() );
		test_cases.push_back( test_case_vfs_two_threads_same_drive_no_lock() );
		test_cases.push_back( test_case_vfs_two_threads_same_file_open_twice() );
		test_cases.push_back( test_case_vfs_writer_and_tail_reader() );
		test_cases.push_back( test_case_mrdb_write_entry_basic() );
		test_cases.push_back( test_case_mrdb_write_entry_overwrite() );
		test_cases.push_back( test_case_mrdb_write_entry_multiple_slots() );
		test_cases.push_back( test_case_simple_ini_compact_float_no_human_readable_comment() );
		test_cases.push_back( test_case_simple_ini_compact_float_roundtrip() );
		test_cases.push_back( test_case_simple_ini_compact_smaller_than_normal() );
		test_cases.push_back( test_case_mrdb_write_entry_compact() );
		test_cases.push_back( test_case_mrdb_write_entry_full_hash() );
		test_cases.push_back( test_case_read_full_dynamic() );
		test_cases.push_back( test_case_read_full_static() );
		test_cases.push_back( test_case_read_full_hash() );
		// AI generated by GitHub Copilot Claude Sonnet 4.6 START
		test_cases.push_back( test_case_cache_static_nonexistent() );
		test_cases.push_back( test_case_cache_dynamic_nonexistent() );
		test_cases.push_back( test_case_cache_write_then_read() );
		test_cases.push_back( test_case_cache_delete_removes_entry() );
		test_cases.push_back( test_case_cache_rename_updates_entry() );
		test_cases.push_back( test_case_cache_invalidate_fallthrough() );
		test_cases.push_back( test_case_cache_static_fixed_memory() );
		test_cases.push_back( test_case_cache_hash_nonexistent() );
		test_cases.push_back( test_case_cache_hash_write_delete_rename() );
		// AI generated by GitHub Copilot Claude Sonnet 4.6 END


        if( o_list_tests.getState() ) {
            std::cout << "Available tests:" << std::endl;
            for( unsigned i = 0; i < test_cases.size(); ++i ) {
                std::cout << Tools::format( "  %2d: %s", i + 1, test_cases[i]->getName() ) << std::endl;
            }
            return 0;
        }

		ColBuilder col;

		const int COL_IDX       = col.addCol( "Idx" );
		const int COL_NAME      = col.addCol( "Test" );
		const int COL_RESULT    = col.addCol( "Result" );
		const int COL_EXPTECTED = col.addCol( "Expected" );
		const int COL_TEST_RES  = col.addCol( "Test Result" );
		const int COL_RUN_TIME  = col.addCol( "Run Time" );

		unsigned idx             = 0;
		bool     something_failed = false;

		std::set<int> these_testcases_only;
		for( auto & v : *o_testcase.getValues() ) {
			these_testcases_only.insert( s2x<int>( v, 0 ) );
		}

		for( auto & test : test_cases ) {
			idx++;

			if( !these_testcases_only.empty() ) {
				if( !these_testcases_only.count( idx ) ) {
					continue;
				}
			}

			CPPDEBUG( Tools::format( "run test: %s", test->getName() ) );

			col.addColData( COL_IDX, Tools::format( "% 2d", idx ) );
			col.addColData( COL_NAME, test->getName() );

			std::string result;
			std::string expected_result = test->getExpectedResult() ? "true" : "false";
			std::string test_result;

			std::chrono::steady_clock::time_point start_time = std::chrono::steady_clock::now();

#if __cpp_exceptions > 0
			try {
#endif
				if( test->throwsException() ) {
					expected_result = "exception";
				}

				result = test->run() ? "true" : "false";

#if __cpp_exceptions > 0
			} catch( const std::exception & error ) {
				result = "exception";
				CPPDEBUG( Tools::format( "Error: %s", error.what() ) );
			} catch( ... ) {
				result = "exception";
				CPPDEBUG( "Error" );
			}
#endif

			if( result != expected_result ) {
				test_result      = co.color_output( ColoredOutput::RED, "failed" );
				something_failed = true;
			} else {
				test_result =
					co.color_output( ColoredOutput::GREEN, "succeeded" );
			}

			std::chrono::steady_clock::time_point end_time = std::chrono::steady_clock::now();
			std::chrono::duration<double> elapsed_seconds = end_time - start_time;

			col.addColData( COL_RUN_TIME, Tools::format( "%.3f ms", elapsed_seconds.count() * 1000.0 ) );
			col.addColData( COL_RESULT, result );
			col.addColData( COL_EXPTECTED, expected_result );
			col.addColData( COL_TEST_RES, test_result );
		}

		std::cout << col.toString() << std::endl;

		if( something_failed ) {
			std::cout << "Complete result: "
			          << co.color_output( ColoredOutput::RED, "FAILED!!" )
			          << std::endl;
			return 1;
		} else {
			std::cout << "Complete result: "
			          << co.color_output( ColoredOutput::GREEN, "succeeded" )
			          << std::endl;
		}

#if __cpp_exceptions > 0
	} catch( const std::exception & error ) {
		std::cout << "Error: " << error.what() << std::endl;
		return 1;
	}
#endif

	return 0;
}
// AI generated by GitHub Copilot Claude Opus 4.7 END
