/*
 * test_vfs_commands.cc
 *
 * One test per command. Each test:
 *   1. Creates a fresh VfsFixture (2 simulated drives + VFS server).
 *   2. Runs a semicolon-separated command sequence matching how
 *      two_drives_dynamic processes its -c argument.
 *   3. Inspects the on-disk drive bin file via dynamic::SimpleFlashFsReadOnly
 *      (same as `simple_flash_fs_tar -i`) to confirm the visible inode/page
 *      layout matches expectations.
 *
 * AI generated by GitHub Copilot Claude Opus 4.7 START
 *  Created on: 12.06.2026
 * AI generated by GitHub Copilot Claude Opus 4.7 END
 */
#include "test_vfs_commands.h"
#include "test_vfs_setup.h"
#include <stderr_exception.h>
#include <CpputilsDebug.h>
#include <format.h>
#include <string_utils.h>
#include <sstream>
#include <thread>
#include <atomic>

using namespace Tools;
using namespace test_vfs;

// AI generated by GitHub Copilot Claude Opus 4.7 START
namespace {

/**
 * TestCaseVfs: wraps a lambda that gets a freshly-constructed
 * VfsFixture. The lambda returns true on success.
 *
 * `expected_result_` defaults to true (normal pass/fail). It can be
 * set to false to register a test that demonstrates a known failing
 * behavior - when the bug gets fixed, the test will start failing
 * (because the actual result no longer matches the expected one) and
 * the developer will know to flip the expectation.
 */
class TestCaseVfs : public TestCaseBase<bool>
{
public:
	using Func = std::function<bool( VfsFixture & fix )>;

private:
	Func func;

public:
	TestCaseVfs( const std::string & name_,
	             Func                func_,
	             bool                expected_result_ = true )
	: TestCaseBase<bool>( name_, expected_result_ ),
	  func( func_ )
	{
	}

	bool run() override
	{
		VfsFixture fix( name );
		return func( fix );
	}
};

/**
 * Format both drives in one shot. Most tests start with this, which
 * matches the typical `format a: ; format b:` two_drives_dynamic
 * preamble.
 */
bool format_both( VfsFixture & fix )
{
	auto r = fix.run( "format a: ; format b: ;" );
	if( !r.all_ok ) {
		CPPDEBUG( Tools::format( "format both failed: %s", r.last_error ) );
		return false;
	}
	return true;
}

bool output_contains( const std::string & haystack, const std::string & needle )
{
	if( haystack.find( needle ) == std::string::npos ) {
		CPPDEBUG( Tools::format( "expected to find '%s' in: '%s'", needle,
		                         haystack ) );
		return false;
	}
	return true;
}

} // namespace
// AI generated by GitHub Copilot Claude Opus 4.7 END

// AI generated by GitHub Copilot Claude Opus 4.7 START
// ---------------------------------------------------------------------------
// format: create a fresh fs on both drives, then inspect to confirm a
// valid header is present (mounted=true) and no user inodes exist.
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_format()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		auto r = fix.run( "format a: ; format b: ;" );
		if( !r.all_ok ) {
			return false;
		}
		if( !output_contains( r.output, "Drive formatted: a" ) ) {
			return false;
		}
		if( !output_contains( r.output, "Drive formatted: b" ) ) {
			return false;
		}

		auto ia = inspect_drive( fix, "a", false );
		auto ib = inspect_drive( fix, "b", false );
		if( !ia.mounted || !ib.mounted ) {
			CPPDEBUG( "post-format: dynamic mount failed" );
			return false;
		}
		if( !ia.inodes.empty() || !ib.inodes.empty() ) {
			CPPDEBUG( "post-format: expected no inodes on either drive" );
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// pwd: when no drive selected returns "/", once `a:` selected returns "/a/"
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_pwd()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		auto r0 = fix.run( "pwd ;" );
		if( !r0.all_ok || r0.output != "/\n" ) {
			CPPDEBUG( Tools::format( "pwd unset: got '%s'", r0.output ) );
			return false;
		}

		if( !format_both( fix ) ) {
			return false;
		}

		auto r1 = fix.run( "a: ; pwd ;" );
		if( !r1.all_ok ) {
			return false;
		}
		if( !output_contains( r1.output, "/a/" ) ) {
			return false;
		}

		auto r2 = fix.run( "b: ; pwd ;" );
		if( !r2.all_ok ) {
			return false;
		}
		if( !output_contains( r2.output, "/b/" ) ) {
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// cd: with no argument lists drives, with argument switches drive
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_cd()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		auto r0 = fix.run( "cd ;" );
		if( !r0.all_ok ) {
			return false;
		}
		if( !output_contains( r0.output, "Available drives" ) ||
		    !output_contains( r0.output, "a" ) ||
		    !output_contains( r0.output, "b" ) ) {
			CPPDEBUG( "cd listing missing drives" );
			return false;
		}

		if( !format_both( fix ) ) {
			return false;
		}

		auto r1 = fix.run( "cd a ; pwd ;" );
		if( !r1.all_ok || !output_contains( r1.output, "/a/" ) ) {
			return false;
		}
		auto r2 = fix.run( "cd /b ; pwd ;" );
		if( !r2.all_ok || !output_contains( r2.output, "/b/" ) ) {
			return false;
		}
		auto r3 = fix.run( "cd a: ; pwd ;" );
		if( !r3.all_ok || !output_contains( r3.output, "/a/" ) ) {
			return false;
		}
		// invalid drive
		auto r4 = fix.run( "cd z ;" );
		if( r4.all_ok ) {
			CPPDEBUG( "cd to non-existent drive should fail" );
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// a: / b: DOS-style change drive
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_dos_change_drive()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		if( !format_both( fix ) ) {
			return false;
		}
		auto r = fix.run( "a: ; pwd ; b: ; pwd ;" );
		if( !r.all_ok ) {
			return false;
		}
		// must contain BOTH /a/ and /b/ in order
		auto a_pos = r.output.find( "/a/" );
		auto b_pos = r.output.find( "/b/" );
		if( a_pos == std::string::npos || b_pos == std::string::npos ||
		    a_pos > b_pos ) {
			CPPDEBUG( Tools::format( "dos change drive: '%s'", r.output ) );
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// touch: create an empty file, confirm inode exists with file_len=0
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_touch()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		if( !format_both( fix ) ) {
			return false;
		}

		auto r = fix.run( "a: ; touch hello.txt ;" );
		if( !r.all_ok ) {
			return false;
		}

		auto ia = inspect_drive( fix, "a" );
		auto * f = find_file( ia, "hello.txt" );
		if( !f ) {
			CPPDEBUG( "touch: file not visible on disk" );
			return false;
		}
		if( f->file_len != 0 ) {
			CPPDEBUG( Tools::format( "touch: expected file_len 0, got %d",
			                         f->file_len ) );
			return false;
		}
		if( f->data_pages_count != 0 ) {
			CPPDEBUG( "touch: expected no external pages" );
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// ls on an empty drive returns "(empty directory)"
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_ls_empty()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		if( !format_both( fix ) ) {
			return false;
		}
		auto r = fix.run( "a: ; ls ;" );
		if( !r.all_ok ) {
			return false;
		}
		if( !output_contains( r.output, "(empty directory)" ) ) {
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// ls after touch: must include the file name and a byte size of 0
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_ls_after_touch()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		if( !format_both( fix ) ) {
			return false;
		}
		auto r = fix.run( "a: ; touch one ; touch two ; ls ;" );
		if( !r.all_ok ) {
			return false;
		}
		if( !output_contains( r.output, "one" ) ||
		    !output_contains( r.output, "two" ) ||
		    !output_contains( r.output, "(0 bytes)" ) ) {
			CPPDEBUG( Tools::format( "ls output: '%s'", r.output ) );
			return false;
		}

		auto ia = inspect_drive( fix, "a" );
		if( !find_file( ia, "one" ) || !find_file( ia, "two" ) ) {
			CPPDEBUG( "ls_after_touch: inspect missing files" );
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// dir: alias for ls -> behaves identically
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_dir_alias()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		if( !format_both( fix ) ) {
			return false;
		}
		auto r = fix.run( "a: ; touch alpha ; dir ;" );
		if( !r.all_ok ) {
			return false;
		}
		if( !output_contains( r.output, "alpha" ) ) {
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// test_count: writes 1..N\n to a file, verify content via dynamic inspect
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_test_count()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		if( !format_both( fix ) ) {
			return false;
		}
		auto r = fix.run( "a: ; test_count count 10 ;" );
		if( !r.all_ok ) {
			return false;
		}

		auto ia  = inspect_drive( fix, "a" );
		auto * f = find_file( ia, "count" );
		if( !f ) {
			CPPDEBUG( "test_count: count file missing" );
			return false;
		}
		std::string expected = "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n";
		if( !bytes_equal( f->contents, expected, "test_count contents" ) ) {
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// cat: writes a file via test_count, reads it back with cat, compares
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_cat()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		if( !format_both( fix ) ) {
			return false;
		}
		auto r = fix.run( "a: ; test_count count 5 ; cat count ;" );
		if( !r.all_ok ) {
			return false;
		}
		std::string expected = "1\n2\n3\n4\n5\n";
		if( !output_contains( r.output, expected ) ) {
			CPPDEBUG( Tools::format( "cat: missing expected substring. got: '%s'",
			                         r.output ) );
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// cp same drive: original file remains, copy is identical
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_cp_same_drive()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		if( !format_both( fix ) ) {
			return false;
		}
		auto r = fix.run(
			"a: ; test_count src 7 ; cp src dst ; cat src ; cat dst ;" );
		if( !r.all_ok ) {
			return false;
		}

		auto ia    = inspect_drive( fix, "a" );
		auto * fs  = find_file( ia, "src" );
		auto * fd  = find_file( ia, "dst" );
		if( !fs || !fd ) {
			CPPDEBUG( "cp_same_drive: src or dst missing on disk" );
			return false;
		}
		std::string expected = "1\n2\n3\n4\n5\n6\n7\n";
		if( !bytes_equal( fs->contents, expected, "src content" ) ) {
			return false;
		}
		if( !bytes_equal( fd->contents, expected, "dst content" ) ) {
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// cp cross drive: write on a:, copy to b: with absolute path
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_cp_cross_drive()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		if( !format_both( fix ) ) {
			return false;
		}
		auto r = fix.run(
			"a: ; test_count payload 4 ; cp /a/payload /b/payload ;" );
		if( !r.all_ok ) {
			return false;
		}

		auto ia    = inspect_drive( fix, "a" );
		auto ib    = inspect_drive( fix, "b" );
		auto * fa  = find_file( ia, "payload" );
		auto * fb  = find_file( ib, "payload" );
		if( !fa || !fb ) {
			CPPDEBUG( "cp_cross_drive: file missing on one side" );
			return false;
		}
		std::string expected = "1\n2\n3\n4\n";
		if( !bytes_equal( fa->contents, expected, "src side" ) ) {
			return false;
		}
		if( !bytes_equal( fb->contents, expected, "dst side" ) ) {
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// mv: rename within drive a:, original is gone, target is present
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_mv_rename()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		if( !format_both( fix ) ) {
			return false;
		}
		auto r = fix.run( "a: ; test_count old 3 ; mv old new ;" );
		if( !r.all_ok ) {
			return false;
		}

		auto ia = inspect_drive( fix, "a" );
		if( find_file( ia, "old" ) ) {
			CPPDEBUG( "mv: old name still visible on disk" );
			return false;
		}
		// mv passes the absolute path /a/new as the new name to
		// rename_file(); accept either the bare or absolute form.
		auto * fn = find_file( ia, "new" );
		if( !fn ) {
			fn = find_file( ia, "/a/new" );
		}
		if( !fn ) {
			CPPDEBUG( "mv: renamed file missing on disk" );
			return false;
		}
		std::string expected = "1\n2\n3\n";
		if( !bytes_equal( fn->contents, expected, "mv content" ) ) {
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// rm: file is deleted and no longer visible
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_rm()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		if( !format_both( fix ) ) {
			return false;
		}
		auto r = fix.run( "a: ; touch doomed ; rm doomed ; ls ;" );
		if( !r.all_ok ) {
			return false;
		}
		if( !output_contains( r.output, "(empty directory)" ) ) {
			CPPDEBUG( Tools::format( "rm: ls did not show empty: '%s'",
			                         r.output ) );
			return false;
		}

		auto ia = inspect_drive( fix, "a" );
		if( find_file( ia, "doomed" ) ) {
			CPPDEBUG( "rm: file still on disk after rm" );
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// help: lists every registered command
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_help()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		auto r = fix.run( "help ;" );
		if( !r.all_ok ) {
			return false;
		}
		// must mention at least the canonical built-ins
		const char * required[] = { "ls",     "cat",    "cp", "mv",
		                            "rm",     "touch",  "cd", "pwd",
		                            "format", "quit",   "help" };
		for( const char * c : required ) {
			if( !output_contains( r.output, c ) ) {
				CPPDEBUG( Tools::format( "help: missing '%s'", c ) );
				return false;
			}
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// quit: stop_execution=true, anything after must not run
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_quit()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		if( !format_both( fix ) ) {
			return false;
		}
		auto r = fix.run( "a: ; quit ; touch must_not_be_created ;" );
		if( !r.all_ok ) {
			return false;
		}
		if( !output_contains( r.output, "Exiting" ) ) {
			return false;
		}

		auto ia = inspect_drive( fix, "a" );
		if( find_file( ia, "must_not_be_created" ) ) {
			CPPDEBUG( "quit: command after quit was executed" );
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// cleanup: create+delete to leave trash, run cleanup, verify it succeeds
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_cleanup()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		if( !format_both( fix ) ) {
			return false;
		}
		auto r = fix.run(
			"a: ; touch a1 ; touch a2 ; rm a1 ; cleanup ; ls ;" );
		if( !r.all_ok ) {
			return false;
		}
		if( !output_contains( r.output, "Cleanup completed" ) ) {
			return false;
		}
		// a2 still present, a1 gone
		if( !output_contains( r.output, "a2" ) ) {
			return false;
		}

		auto ia = inspect_drive( fix, "a" );
		if( find_file( ia, "a1" ) ) {
			CPPDEBUG( "cleanup: deleted file still on disk" );
			return false;
		}
		if( !find_file( ia, "a2" ) ) {
			CPPDEBUG( "cleanup: surviving file is missing" );
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// test1_full_flow: reproduces the exact two_drives_dynamic test1
// command sequence: format a: ; a: ; test_count count 74 ; cat count ;
// quit ;  - end-to-end smoke test bypassing the C wrapper.
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_vfs_test1_full_flow()
{
	return std::make_shared<TestCaseVfs>( __FUNCTION__, []( VfsFixture & fix ) {
		auto r = fix.run(
			"format a: ; a: ; test_count count 74 ; cat count ; quit ;" );
		if( !r.all_ok ) {
			return false;
		}

		// build expected "1\n2\n...\n74\n"
		std::ostringstream expected;
		for( int i = 1; i <= 74; i++ ) {
			expected << i << "\n";
		}
		std::string exp = expected.str();

		if( !output_contains( r.output, exp ) ) {
			CPPDEBUG( Tools::format(
				"full_flow: cat output missing expected sequence. got: '%s'",
				r.output ) );
			return false;
		}

		auto ia  = inspect_drive( fix, "a" );
		auto * f = find_file( ia, "count" );
		if( !f ) {
			CPPDEBUG( "full_flow: count file missing" );
			return false;
		}
		if( !bytes_equal( f->contents, exp, "full_flow count content" ) ) {
			return false;
		}
		return true;
	} );
}

// ---------------------------------------------------------------------------
// Two threads, same drive, two DIFFERENT files, opened from each thread.
//
// Spawns two writer threads that each open() / write() / close() their
// own file on drive a: in a tight loop. Both threads go through the
// SAME FramFsImplDetail (one fs instance, one mem simulator).
//
// Originally this test was registered with expected_result=false to
// DOCUMENT the missing locking - it "succeeded" while the locking
// bug was present (races -> result=false matched expected=false).
//
// After:
//   * adding fine-grained per-resource mutexes inside
//     SimpleFlashFsBase (m_inode_meta_mutex / m_free_data_pages_mutex
//     / m_max_inode_number_mutex / m_mem_mutex),
//   * fixing the allocated_unwritten_pages leak in
//     erase_inode_and_unused_pages(),
//   * fixing the data-page leak by stripping Deleted entries before
//     serialising the new inode in flush(), and
//   * giving SimFlashFsFlashMemory an internal mutex (the std::fstream
//     simulator is fundamentally not thread-safe),
// this scenario now produces correct, byte-exact concatenated output
// on disk - so the expectation flips to true.
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>>
test_case_vfs_two_threads_same_drive_no_lock()
{
	return std::make_shared<TestCaseVfs>(
		__FUNCTION__,
		[]( VfsFixture & fix ) {
			if( !format_both( fix ) ) {
				CPPDEBUG( "two-thread: pre-flight format failed" );
				return false;
			}

			constexpr int N = 200;

			std::atomic<int>  errors_a     {0};
			std::atomic<int>  errors_b     {0};
			std::atomic<bool> writer_threw {false};

			auto writer = [&]( const std::string & abs_path,
			                   char                tag,
			                   std::atomic<int> &  errors ) {
				for( int i = 1; i <= N; i++ ) {
					try {
						auto h = fix.vfs->open(
							abs_path,
							std::ios::out | std::ios::app );
						if( !h || !h->valid() ) {
							errors++;
							continue;
						}
						std::string line =
							std::string( 1, tag ) +
							std::to_string( i ) + "\n";
						auto * data = reinterpret_cast<std::byte *>(
							line.data() );
						if( h->write( data, line.size() ) != line.size() ) {
							errors++;
						}
						h->flush();
					} catch( const std::exception & e ) {
						writer_threw = true;
						errors++;
						CPPDEBUG( Tools::format(
							"two-thread '%c' iteration %d threw: %s",
							tag, i, e.what() ) );
					} catch( ... ) {
						writer_threw = true;
						errors++;
					}
				}
			};

			std::thread ta( writer, "/a/twothreads_A", 'A',
			                std::ref( errors_a ) );
			std::thread tb( writer, "/a/twothreads_B", 'B',
			                std::ref( errors_b ) );
			ta.join();
			tb.join();

			if( writer_threw ) {
				CPPDEBUG(
					"two-thread: at least one writer caught an exception" );
				return false; // race observed
			}
			if( errors_a > 0 || errors_b > 0 ) {
				CPPDEBUG( Tools::format(
					"two-thread: write errors a=%d b=%d",
					errors_a.load(), errors_b.load() ) );
				return false;
			}

			// build expected contents
			std::ostringstream exp_a, exp_b;
			for( int i = 1; i <= N; i++ ) {
				exp_a << "A" << i << "\n";
				exp_b << "B" << i << "\n";
			}
			std::string sa = exp_a.str();
			std::string sb = exp_b.str();

			DriveInspect ia;
			try {
				ia = inspect_drive( fix, "a" );
			} catch( const std::exception & e ) {
				CPPDEBUG( Tools::format(
					"two-thread: inspect threw '%s'", e.what() ) );
				return false;
			}

			if( !ia.mounted ) {
				CPPDEBUG(
					"two-thread: dynamic re-mount of drive a failed" );
				return false;
			}

			auto * fa = find_file( ia, "twothreads_A" );
			auto * fb = find_file( ia, "twothreads_B" );
			if( !fa || !fb ) {
				CPPDEBUG( Tools::format(
					"two-thread: missing file(s) a=%d b=%d",
					(fa != nullptr), (fb != nullptr) ) );
				return false;
			}

			if( !bytes_equal( fa->contents, sa,
			                  "twothreads_A content" ) ) {
				return false;
			}
			if( !bytes_equal( fb->contents, sb,
			                  "twothreads_B content" ) ) {
				return false;
			}

			// All checks passed - both files have the exact expected
			// contents. With the locking and FS fixes in place this
			// is now the normal outcome, so expected_result == true.
			return true;
		},
		/* expected_result */ true );
}

// ---------------------------------------------------------------------------
// Two threads, SAME drive, SAME file, opened twice (open-file-table proof).
//
// Each thread opens "/a/shared" exactly ONCE and keeps its handle
// alive for the whole loop. Because both opens are simultaneously
// live, SimpleFlashFsThreadedVfsServer's open-file table returns
// ThreadedFileHandles that share ONE underlying drive file handle
// (one OpenFile). Every read / write / flush is serialised by the
// per-OpenFile mutex, and every append-write does an explicit seek
// to the current file_size INSIDE the locked region. So the on-disk
// file is the byte-exact concatenation of all writes in some
// thread-interleaving order.
//
// Each line is fixed-width "AAAAA"/"BBBBB" (5 bytes including the
// trailing newline) so we can validate the line count, the line
// integrity (no torn / interleaved bytes), and the total size.
//
// Registered with expected_result = true: this test PROVES the
// open-file table works. N is intentionally modest because every
// flush() does a COW on an inode page on the small (32 KB) Drive A.
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>>
test_case_vfs_two_threads_same_file_open_twice()
{
	return std::make_shared<TestCaseVfs>(
		__FUNCTION__,
		[]( VfsFixture & fix ) {
			if( !format_both( fix ) ) {
				CPPDEBUG( "open-twice: format failed" );
				return false;
			}

			constexpr int N = 50;

			std::atomic<int>  errors_a     {0};
			std::atomic<int>  errors_b     {0};
			std::atomic<bool> writer_threw {false};
			std::atomic<int>  ready        {0};

			auto writer = [&]( char tag, std::atomic<int> & errors ) {
				auto h = fix.vfs->open(
					"/a/shared",
					std::ios::out | std::ios::app );
				if( !h || !h->valid() ) {
					errors += N;
					ready++;
					return;
				}

				// Wait until the SIBLING thread has also opened the
				// file before either of us starts writing - that
				// way the open-file table is provably shared while
				// both writers are active.
				ready++;
				while( ready.load() < 2 ) {
					std::this_thread::yield();
				}

				for( int i = 0; i < N; i++ ) {
					try {
						char buf[6] = { tag, tag, tag, tag, '\n', 0 };
						auto * data = reinterpret_cast<std::byte *>( buf );
						if( h->write( data, 5 ) != 5 ) {
							errors++;
						}
						h->flush();
					} catch( const std::exception & e ) {
						writer_threw = true;
						errors++;
						CPPDEBUG( Tools::format(
							"open-twice '%c' iteration %d threw: %s",
							tag, i, e.what() ) );
					} catch( ... ) {
						writer_threw = true;
						errors++;
					}
				}
			};

			std::thread ta( writer, 'A', std::ref( errors_a ) );
			std::thread tb( writer, 'B', std::ref( errors_b ) );
			ta.join();
			tb.join();

			if( writer_threw ) {
				CPPDEBUG( "open-twice: a writer threw" );
				return false;
			}
			if( errors_a > 0 || errors_b > 0 ) {
				CPPDEBUG( Tools::format(
					"open-twice: write errors a=%d b=%d",
					errors_a.load(), errors_b.load() ) );
				return false;
			}

			DriveInspect ia;
			try {
				ia = inspect_drive( fix, "a" );
			} catch( const std::exception & e ) {
				CPPDEBUG( Tools::format(
					"open-twice: inspect threw '%s'", e.what() ) );
				return false;
			}
			if( !ia.mounted ) {
				CPPDEBUG( "open-twice: dynamic remount of drive a failed" );
				return false;
			}

			auto * f = find_file( ia, "shared" );
			if( !f ) {
				CPPDEBUG( "open-twice: shared file missing on disk" );
				return false;
			}

			const std::size_t expected_bytes = 2 * N * 5;
			if( f->contents.size() != expected_bytes ) {
				CPPDEBUG( Tools::format(
					"open-twice: wrong size on disk got=%d expected=%d",
					f->contents.size(), expected_bytes ) );
				return false;
			}

			int count_a = 0, count_b = 0;
			for( std::size_t off = 0; off < f->contents.size(); off += 5 ) {
				const auto b0 = static_cast<char>( f->contents[off + 0] );
				const auto b1 = static_cast<char>( f->contents[off + 1] );
				const auto b2 = static_cast<char>( f->contents[off + 2] );
				const auto b3 = static_cast<char>( f->contents[off + 3] );
				const auto b4 = static_cast<char>( f->contents[off + 4] );

				if( b4 != '\n' ) {
					CPPDEBUG( Tools::format(
						"open-twice: line at offset %d not terminated",
						off ) );
					return false;
				}
				if( b0 == 'A' && b1 == 'A' && b2 == 'A' && b3 == 'A' ) {
					count_a++;
				} else if( b0 == 'B' && b1 == 'B' && b2 == 'B' && b3 == 'B' ) {
					count_b++;
				} else {
					CPPDEBUG( Tools::format(
						"open-twice: garbled line at offset %d: '%c%c%c%c'",
						off, b0, b1, b2, b3 ) );
					return false;
				}
			}

			if( count_a != N || count_b != N ) {
				CPPDEBUG( Tools::format(
					"open-twice: line counts wrong a=%d b=%d (each expected %d)",
					count_a, count_b, N ) );
				return false;
			}

			return true;
		},
		/* expected_result */ true );
}
// AI generated by GitHub Copilot Claude Opus 4.7 END

