/*
 * test_mrdb_write_entry.h
 *
 * Tests for the write_entry() mechanism used by
 * Measurement_Result_Database_v3::write_entry() from
 * SVM_1001_Measurement_Application/Memory/Measurement_Result_Database_v3.cpp
 *
 * The tests exercise the SimpleIni + FileBuffer on-VFS-file pattern
 * directly, covering all three INI sections ([dict], [cfg], [result])
 * written by write_entry().
 *
 * AI generated by GitHub Copilot Claude Sonnet 4.6 START
 *  Created on: 30.06.2026
 * AI generated by GitHub Copilot Claude Sonnet 4.6 END
 */
#pragma once

#include <TestUtils.h>
#include <memory>

// AI generated by GitHub Copilot Claude Sonnet 4.6 START
std::shared_ptr<TestCaseBase<bool>> test_case_mrdb_write_entry_basic();
std::shared_ptr<TestCaseBase<bool>> test_case_mrdb_write_entry_overwrite();
std::shared_ptr<TestCaseBase<bool>> test_case_mrdb_write_entry_multiple_slots();
std::shared_ptr<TestCaseBase<bool>> test_case_mrdb_write_entry_compact();
std::shared_ptr<TestCaseBase<bool>> test_case_mrdb_write_entry_full();
// AI generated by GitHub Copilot Claude Sonnet 4.6 END
