/*
 * test_simple_ini_compact.h
 *
 * Tests for SimpleIni::properties_t::compact_file_format = true.
 *
 * AI generated by GitHub Copilot Claude Sonnet 4.6 START
 *  Created on: 30.06.2026
 * AI generated by GitHub Copilot Claude Sonnet 4.6 END
 */
#pragma once

#include <TestUtils.h>
#include <memory>

// AI generated by GitHub Copilot Claude Sonnet 4.6 START
std::shared_ptr<TestCaseBase<bool>> test_case_simple_ini_compact_float_no_human_readable_comment();
std::shared_ptr<TestCaseBase<bool>> test_case_simple_ini_compact_float_roundtrip();
std::shared_ptr<TestCaseBase<bool>> test_case_simple_ini_compact_smaller_than_normal();
// AI generated by GitHub Copilot Claude Sonnet 4.6 END
