/*
 * test_file_name_cache.h
 *
 * Test cases for the optional filename cache in FramFsImplDetail.
 * Covers both FramFsFileNameCacheStatic and FramFsFileNameCacheDynamic,
 * as well as the cache invalidation / rename / delete paths.
 *
 * AI generated by GitHub Copilot Claude Sonnet 4.6 START
 *  Created on: 07.07.2026
 * AI generated by GitHub Copilot Claude Sonnet 4.6 END
 */
#pragma once

#include <TestUtils.h>
#include <memory>

// AI generated by GitHub Copilot Claude Sonnet 4.6 START

/** Static cache: open 100 non-existent files - must all return nullptr. */
std::shared_ptr<TestCaseBase<bool>> test_case_cache_static_nonexistent();

/** Dynamic cache: open 100 non-existent files - must all return nullptr. */
std::shared_ptr<TestCaseBase<bool>> test_case_cache_dynamic_nonexistent();

/** After writing a file, might_exist() must return true; file is readable. */
std::shared_ptr<TestCaseBase<bool>> test_case_cache_write_then_read();

/** After deleting a file, might_exist() must return false; open returns nullptr. */
std::shared_ptr<TestCaseBase<bool>> test_case_cache_delete_removes_entry();

/** After renaming, old name is absent in cache; new name is present. */
std::shared_ptr<TestCaseBase<bool>> test_case_cache_rename_updates_entry();

/** Invalidating the cache causes all opens to fall through to flash (still correct). */
std::shared_ptr<TestCaseBase<bool>> test_case_cache_invalidate_fallthrough();

/** Static cache memory is one contiguous pre-allocated block. */
std::shared_ptr<TestCaseBase<bool>> test_case_cache_static_fixed_memory();

/** Hash cache: 100 non-existent files must all return nullptr (empty FS). */
std::shared_ptr<TestCaseBase<bool>> test_case_cache_hash_nonexistent();

/** Hash cache: write / delete / rename cycle — cache stays consistent. */
std::shared_ptr<TestCaseBase<bool>> test_case_cache_hash_write_delete_rename();

// AI generated by GitHub Copilot Claude Sonnet 4.6 END
