/*
 * test_file_name_cache.cc
 *
 * Test cases for the FramFsImplDetail filename cache.
 *
 * AI generated by GitHub Copilot Claude Sonnet 4.6 START
 *  Created on: 07.07.2026
 * AI generated by GitHub Copilot Claude Sonnet 4.6 END
 */

#include "test_file_name_cache.h"
#include "test_vfs_setup.h"
#include "../simpleflashfs/src_vfs/FramFsFileNameCache.h"
#include "../simpleflashfs/src_vfs/FramFsImplDetail.h"
#include <CpputilsDebug.h>
#include <format.h>

using namespace Tools;
using namespace test_vfs;
using namespace SimpleFlashFs::Vfs;

// AI generated by GitHub Copilot Claude Sonnet 4.6 START
namespace {

// ---------------------------------------------------------------------------
// TestCaseCacheLambda - same VfsFixture pattern used by other test files
// ---------------------------------------------------------------------------
class TestCaseCacheLambda : public TestCaseBase<bool>
{
public:
    using Func = std::function<bool( VfsFixture & )>;

private:
    Func func;

public:
    TestCaseCacheLambda( const std::string & name_, Func func_,
                         bool expected_result_ = true )
    : TestCaseBase<bool>( name_, expected_result_ ),
      func( func_ )
    {}

    bool run() override
    {
        VfsFixture fix( name );
        return func( fix );
    }
};

// ---------------------------------------------------------------------------
// Helper: write a small file to drive b
// ---------------------------------------------------------------------------
static bool write_file( SimpleFlashFs::Vfs::VfsServerInterface & vfs,
                        const std::string & path,
                        const std::string & content )
{
    auto fh = vfs.open( path, std::ios::out | std::ios::trunc );
    if( !fh ) {
        CPPDEBUG( Tools::format( "write_file: cannot create %s", path ) );
        return false;
    }
    const auto * data = reinterpret_cast<const std::byte *>( content.data() );
    fh->write( data, content.size() );
    return fh->flush();
}

} // namespace
// AI generated by GitHub Copilot Claude Sonnet 4.6 END

// ---------------------------------------------------------------------------
// test_case_cache_static_nonexistent
// ---------------------------------------------------------------------------
// AI generated by GitHub Copilot Claude Sonnet 4.6 START
std::shared_ptr<TestCaseBase<bool>> test_case_cache_static_nonexistent()
{
    return std::make_shared<TestCaseCacheLambda>( __FUNCTION__,
        []( VfsFixture & fix ) -> bool {
            if( !fix.run( "format a: ; format b: ;" ).all_ok ) {
                CPPDEBUG( "test_case_cache_static_nonexistent: format failed" );
                return false;
            }

            // Install static cache on drive b
            fix.drive_b->set_name_cache( std::make_unique<FramFsFileNameCacheStatic>() );

            if( !fix.drive_b->get_name_cache() || !fix.drive_b->get_name_cache()->is_valid() ) {
                CPPDEBUG( "test_case_cache_static_nonexistent: cache not valid after install" );
                return false;
            }

            // Try to open 100 non-existent files - all must return nullptr
            for( unsigned n = 1; n <= 100; ++n ) {
                const std::string path = Tools::format( "/b/measurements/%04u.ini", n );
                auto fh = fix.vfs->open( path, std::ios::in );
                if( fh ) {
                    CPPDEBUG( Tools::format( "test_case_cache_static_nonexistent: unexpectedly opened %s", path ) );
                    return false;
                }
            }

            // Cache must still report these names as absent
            for( unsigned n = 1; n <= 100; ++n ) {
                const std::string name = Tools::format( "measurements/%04u.ini", n );
                if( fix.drive_b->get_name_cache()->might_exist( name ) ) {
                    CPPDEBUG( Tools::format( "test_case_cache_static_nonexistent: might_exist returned true for absent '%s'", name ) );
                    return false;
                }
            }

            return true;
        } );
}
// AI generated by GitHub Copilot Claude Sonnet 4.6 END

// ---------------------------------------------------------------------------
// test_case_cache_dynamic_nonexistent
// ---------------------------------------------------------------------------
// AI generated by GitHub Copilot Claude Sonnet 4.6 START
std::shared_ptr<TestCaseBase<bool>> test_case_cache_dynamic_nonexistent()
{
    return std::make_shared<TestCaseCacheLambda>( __FUNCTION__,
        []( VfsFixture & fix ) -> bool {
            if( !fix.run( "format a: ; format b: ;" ).all_ok ) {
                CPPDEBUG( "test_case_cache_dynamic_nonexistent: format failed" );
                return false;
            }

            fix.drive_b->set_name_cache( std::make_unique<FramFsFileNameCacheDynamic>() );

            if( !fix.drive_b->get_name_cache() || !fix.drive_b->get_name_cache()->is_valid() ) {
                CPPDEBUG( "test_case_cache_dynamic_nonexistent: cache not valid after install" );
                return false;
            }

            for( unsigned n = 1; n <= 100; ++n ) {
                const std::string path = Tools::format( "/b/ghost/%04u.dat", n );
                auto fh = fix.vfs->open( path, std::ios::in );
                if( fh ) {
                    CPPDEBUG( Tools::format( "test_case_cache_dynamic_nonexistent: unexpectedly opened %s", path ) );
                    return false;
                }
            }

            return true;
        } );
}
// AI generated by GitHub Copilot Claude Sonnet 4.6 END

// ---------------------------------------------------------------------------
// test_case_cache_write_then_read
// ---------------------------------------------------------------------------
// AI generated by GitHub Copilot Claude Sonnet 4.6 START
std::shared_ptr<TestCaseBase<bool>> test_case_cache_write_then_read()
{
    return std::make_shared<TestCaseCacheLambda>( __FUNCTION__,
        []( VfsFixture & fix ) -> bool {
            if( !fix.run( "format a: ; format b: ;" ).all_ok ) {
                CPPDEBUG( "test_case_cache_write_then_read: format failed" );
                return false;
            }

            fix.drive_b->set_name_cache( std::make_unique<FramFsFileNameCacheDynamic>() );

            // Before write: file should not be in cache
            if( fix.drive_b->get_name_cache()->might_exist( "data/hello.txt" ) ) {
                CPPDEBUG( "test_case_cache_write_then_read: file unexpectedly pre-cached" );
                return false;
            }

            // Write the file
            if( !write_file( *fix.vfs, "/b/data/hello.txt", "hello cache" ) ) {
                CPPDEBUG( "test_case_cache_write_then_read: write failed" );
                return false;
            }

            // Cache should now report the file as potentially present
            if( !fix.drive_b->get_name_cache()->might_exist( "data/hello.txt" ) ) {
                CPPDEBUG( "test_case_cache_write_then_read: might_exist false after write" );
                return false;
            }

            // Read back: must succeed
            auto fh = fix.vfs->open( "/b/data/hello.txt", std::ios::in );
            if( !fh ) {
                CPPDEBUG( "test_case_cache_write_then_read: cannot re-open written file" );
                return false;
            }

            std::string buf( 11, '\0' );
            fh->read( reinterpret_cast<std::byte *>( buf.data() ), 11 );
            if( buf != "hello cache" ) {
                CPPDEBUG( Tools::format( "test_case_cache_write_then_read: content mismatch '%s'", buf ) );
                return false;
            }

            return true;
        } );
}
// AI generated by GitHub Copilot Claude Sonnet 4.6 END

// ---------------------------------------------------------------------------
// test_case_cache_delete_removes_entry
// ---------------------------------------------------------------------------
// AI generated by GitHub Copilot Claude Sonnet 4.6 START
std::shared_ptr<TestCaseBase<bool>> test_case_cache_delete_removes_entry()
{
    return std::make_shared<TestCaseCacheLambda>( __FUNCTION__,
        []( VfsFixture & fix ) -> bool {
            if( !fix.run( "format a: ; format b: ;" ).all_ok ) {
                CPPDEBUG( "test_case_cache_delete_removes_entry: format failed" );
                return false;
            }

            fix.drive_b->set_name_cache( std::make_unique<FramFsFileNameCacheDynamic>() );

            // Write a file
            if( !write_file( *fix.vfs, "/b/to_delete.txt", "bye" ) ) {
                CPPDEBUG( "test_case_cache_delete_removes_entry: write failed" );
                return false;
            }

            if( !fix.drive_b->get_name_cache()->might_exist( "to_delete.txt" ) ) {
                CPPDEBUG( "test_case_cache_delete_removes_entry: not in cache after write" );
                return false;
            }

            // Delete via file handle
            {
                auto fh = fix.vfs->open( "/b/to_delete.txt", std::ios::in );
                if( !fh ) {
                    CPPDEBUG( "test_case_cache_delete_removes_entry: cannot open for delete" );
                    return false;
                }
                if( !fh->delete_file() ) {
                    CPPDEBUG( "test_case_cache_delete_removes_entry: delete_file failed" );
                    return false;
                }
            }

            // Cache must now report the file as absent
            if( fix.drive_b->get_name_cache()->might_exist( "to_delete.txt" ) ) {
                CPPDEBUG( "test_case_cache_delete_removes_entry: might_exist still true after delete" );
                return false;
            }

            // Opening it again must also fail (flash confirms absent)
            auto fh2 = fix.vfs->open( "/b/to_delete.txt", std::ios::in );
            if( fh2 ) {
                CPPDEBUG( "test_case_cache_delete_removes_entry: file still openable after delete" );
                return false;
            }

            return true;
        } );
}
// AI generated by GitHub Copilot Claude Sonnet 4.6 END

// ---------------------------------------------------------------------------
// test_case_cache_rename_updates_entry
// ---------------------------------------------------------------------------
// AI generated by GitHub Copilot Claude Sonnet 4.6 START
std::shared_ptr<TestCaseBase<bool>> test_case_cache_rename_updates_entry()
{
    return std::make_shared<TestCaseCacheLambda>( __FUNCTION__,
        []( VfsFixture & fix ) -> bool {
            if( !fix.run( "format a: ; format b: ;" ).all_ok ) {
                CPPDEBUG( "test_case_cache_rename_updates_entry: format failed" );
                return false;
            }

            fix.drive_b->set_name_cache( std::make_unique<FramFsFileNameCacheDynamic>() );

            // Write original file
            if( !write_file( *fix.vfs, "/b/old_name.txt", "rename me" ) ) {
                CPPDEBUG( "test_case_cache_rename_updates_entry: write failed" );
                return false;
            }

            if( !fix.drive_b->get_name_cache()->might_exist( "old_name.txt" ) ) {
                CPPDEBUG( "test_case_cache_rename_updates_entry: old_name not in cache" );
                return false;
            }

            // Rename via file handle
            {
                auto fh = fix.vfs->open( "/b/old_name.txt", std::ios::in );
                if( !fh ) {
                    CPPDEBUG( "test_case_cache_rename_updates_entry: cannot open for rename" );
                    return false;
                }
                if( !fh->rename_file( "new_name.txt" ) ) {
                    CPPDEBUG( "test_case_cache_rename_updates_entry: rename_file failed" );
                    return false;
                }
            }

            // Old name must be absent in cache
            if( fix.drive_b->get_name_cache()->might_exist( "old_name.txt" ) ) {
                CPPDEBUG( "test_case_cache_rename_updates_entry: old_name still in cache after rename" );
                return false;
            }

            // New name must be present
            if( !fix.drive_b->get_name_cache()->might_exist( "new_name.txt" ) ) {
                CPPDEBUG( "test_case_cache_rename_updates_entry: new_name not in cache after rename" );
                return false;
            }

            // Verify flash: open new name succeeds, old name fails
            auto fh_new = fix.vfs->open( "/b/new_name.txt", std::ios::in );
            if( !fh_new ) {
                CPPDEBUG( "test_case_cache_rename_updates_entry: cannot open new_name on flash" );
                return false;
            }

            auto fh_old = fix.vfs->open( "/b/old_name.txt", std::ios::in );
            if( fh_old ) {
                CPPDEBUG( "test_case_cache_rename_updates_entry: old_name still openable on flash" );
                return false;
            }

            return true;
        } );
}
// AI generated by GitHub Copilot Claude Sonnet 4.6 END

// ---------------------------------------------------------------------------
// test_case_cache_invalidate_fallthrough
// ---------------------------------------------------------------------------
// AI generated by GitHub Copilot Claude Sonnet 4.6 START
std::shared_ptr<TestCaseBase<bool>> test_case_cache_invalidate_fallthrough()
{
    return std::make_shared<TestCaseCacheLambda>( __FUNCTION__,
        []( VfsFixture & fix ) -> bool {
            if( !fix.run( "format a: ; format b: ;" ).all_ok ) {
                CPPDEBUG( "test_case_cache_invalidate_fallthrough: format failed" );
                return false;
            }

            fix.drive_b->set_name_cache( std::make_unique<FramFsFileNameCacheDynamic>() );

            // Write two files
            if( !write_file( *fix.vfs, "/b/alpha.txt", "alpha" ) ) {
                return false;
            }
            if( !write_file( *fix.vfs, "/b/beta.txt", "beta" ) ) {
                return false;
            }

            // Invalidate the cache
            fix.drive_b->get_name_cache()->invalidate();

            if( fix.drive_b->get_name_cache()->is_valid() ) {
                CPPDEBUG( "test_case_cache_invalidate_fallthrough: cache still valid after invalidate" );
                return false;
            }

            // After invalidation, might_exist must return true for everything
            // (conservative fallback), but flash reads must still be correct.
            if( !fix.drive_b->get_name_cache()->might_exist( "alpha.txt" ) ) {
                CPPDEBUG( "test_case_cache_invalidate_fallthrough: might_exist false after invalidate (should be true)" );
                return false;
            }
            if( !fix.drive_b->get_name_cache()->might_exist( "nonexistent.txt" ) ) {
                CPPDEBUG( "test_case_cache_invalidate_fallthrough: might_exist false for nonexistent after invalidate" );
                return false;
            }

            // Opens still work correctly via flash fallthrough
            auto fh_a = fix.vfs->open( "/b/alpha.txt", std::ios::in );
            if( !fh_a ) {
                CPPDEBUG( "test_case_cache_invalidate_fallthrough: alpha.txt not found on flash" );
                return false;
            }

            auto fh_x = fix.vfs->open( "/b/nonexistent.txt", std::ios::in );
            if( fh_x ) {
                CPPDEBUG( "test_case_cache_invalidate_fallthrough: nonexistent.txt unexpectedly found" );
                return false;
            }

            return true;
        } );
}
// AI generated by GitHub Copilot Claude Sonnet 4.6 END

// ---------------------------------------------------------------------------
// test_case_cache_static_fixed_memory
// ---------------------------------------------------------------------------
// AI generated by GitHub Copilot Claude Sonnet 4.6 START
std::shared_ptr<TestCaseBase<bool>> test_case_cache_static_fixed_memory()
{
    return std::make_shared<TestCaseCacheLambda>( __FUNCTION__,
        []( VfsFixture & fix ) -> bool {
            if( !fix.run( "format a: ; format b: ;" ).all_ok ) {
                CPPDEBUG( "test_case_cache_static_fixed_memory: format failed" );
                return false;
            }

            // Install static cache, write several files, delete some, rename one.
            fix.drive_b->set_name_cache( std::make_unique<FramFsFileNameCacheStatic>() );

            auto * cache = fix.drive_b->get_name_cache();
            if( !cache || !cache->is_valid() ) {
                CPPDEBUG( "test_case_cache_static_fixed_memory: cache not valid" );
                return false;
            }

            // Write 5 files
            for( unsigned n = 1; n <= 5; ++n ) {
                const std::string path = Tools::format( "/b/file%02u.bin", n );
                if( !write_file( *fix.vfs, path, "data" ) ) {
                    CPPDEBUG( Tools::format( "test_case_cache_static_fixed_memory: write %u failed", n ) );
                    return false;
                }
            }

            // All 5 should be in cache
            for( unsigned n = 1; n <= 5; ++n ) {
                const std::string name = Tools::format( "file%02u.bin", n );
                if( !cache->might_exist( name ) ) {
                    CPPDEBUG( Tools::format( "test_case_cache_static_fixed_memory: %s not in cache", name ) );
                    return false;
                }
            }

            // Delete file02.bin
            {
                auto fh = fix.vfs->open( "/b/file02.bin", std::ios::in );
                if( !fh ) {
                    CPPDEBUG( "test_case_cache_static_fixed_memory: cannot open file02.bin for delete" );
                    return false;
                }
                fh->delete_file();
            }
            if( cache->might_exist( "file02.bin" ) ) {
                CPPDEBUG( "test_case_cache_static_fixed_memory: file02.bin still in cache after delete" );
                return false;
            }

            // Rename file03.bin → file03_renamed.bin
            {
                auto fh = fix.vfs->open( "/b/file03.bin", std::ios::in );
                if( !fh ) {
                    CPPDEBUG( "test_case_cache_static_fixed_memory: cannot open file03.bin for rename" );
                    return false;
                }
                fh->rename_file( "file03_renamed.bin" );
            }
            if( cache->might_exist( "file03.bin" ) ) {
                CPPDEBUG( "test_case_cache_static_fixed_memory: file03.bin still in cache after rename" );
                return false;
            }
            if( !cache->might_exist( "file03_renamed.bin" ) ) {
                CPPDEBUG( "test_case_cache_static_fixed_memory: file03_renamed.bin not in cache" );
                return false;
            }

            // Non-existent files must not be in cache
            if( cache->might_exist( "file99.bin" ) ) {
                CPPDEBUG( "test_case_cache_static_fixed_memory: file99.bin wrongly in cache" );
                return false;
            }

            return true;
        } );
}
// AI generated by GitHub Copilot Claude Sonnet 4.6 END
