/*
 * test_vfs_setup.cc
 *
 * AI generated by GitHub Copilot Claude Opus 4.7 START
 *  Created on: 12.06.2026
 * AI generated by GitHub Copilot Claude Opus 4.7 END
 */
#include "test_vfs_setup.h"
#include "../simpleflashfs/src_simple_flash_fs_tar/SimpleFlashFsDynamicReadOnly.h"
#include <stderr_exception.h>
#include <CpputilsDebug.h>
#include <format.h>
#include <string_utils.h>
#include <filesystem>

using namespace Tools;
using namespace SimpleFlashFs;
using namespace SimpleFlashFs::dynamic;
using namespace SimpleFlashFs::SimPc;

namespace test_vfs {

// AI generated by GitHub Copilot Claude Opus 4.7 START
namespace {

/**
 * test_vfs_quit: a private "quit" command that does nothing visible
 * to the test code but still satisfies the parser's registration so
 * tests can use the same command set as two_drives_dynamic.
 */
class TestCmdQuit : public SimpleFlashFs::Vfs::Command
{
public:
	SimpleFlashFs::Vfs::CommandResult execute( const std::vector<std::string> & /*args*/ ) override {
		return {true, "OK", "Exiting...\n", true};
	}
	std::string get_description() const override { return "Quit the program"; }
	std::string get_usage() const override { return "quit  - Exit the program"; }
};

/**
 * test_vfs_cleanup: forwards to vfs->cleanup(); identical to
 * two_drives_dynamic's CommandCleanup.
 */
class TestCmdCleanup : public SimpleFlashFs::Vfs::FilesystemCommand
{
public:
	using FilesystemCommand::FilesystemCommand;
	SimpleFlashFs::Vfs::CommandResult execute( const std::vector<std::string> & /*args*/ ) override {
		m_vfs->cleanup();
		return {true, "OK", "Cleanup completed.\n"};
	}
	std::string get_description() const override { return "Perform cleanup operations"; }
	std::string get_usage() const override { return "cleanup  - Perform cleanup operations"; }
};

} // namespace
// AI generated by GitHub Copilot Claude Opus 4.7 END

// AI generated by GitHub Copilot Claude Opus 4.7 START
void FramFsDriveA::create()
{
	auto header = ::SimpleFlashFs::dynamic::SimpleFlashFs::create_default_header(
		DRIVE_A_FM_25_W_256_PAGE_SIZE,
		DRIVE_A_FM_25_W_256_SIZE / DRIVE_A_FM_25_W_256_PAGE_SIZE );

	if( !::SimpleFlashFs::dynamic::SimpleFlashFs::create( header ) ) {
		throw STDERR_EXCEPTION( "cannot create drive a" );
	}
}

void FramFsDriveB::create()
{
	auto header = ::SimpleFlashFs::dynamic::SimpleFlashFs::create_default_header(
		DRIVE_B_AT45_DB321E_PAGE_SIZE,
		DRIVE_B_AT45_DB321E_SIZE / DRIVE_B_AT45_DB321E_PAGE_SIZE );

	if( !::SimpleFlashFs::dynamic::SimpleFlashFs::create( header ) ) {
		throw STDERR_EXCEPTION( "cannot create drive b" );
	}
}
// AI generated by GitHub Copilot Claude Opus 4.7 END

// AI generated by GitHub Copilot Claude Opus 4.7 START
VfsFixture::VfsFixture( const std::string & name_prefix )
: drive_a_path( "." + name_prefix + "_drive_a" ),
  drive_b_path( "." + name_prefix + "_drive_b" )
{
	// scrub previous runs
	std::error_code ec;
	std::filesystem::remove( drive_a_path, ec );
	std::filesystem::remove( drive_b_path, ec );

	mem_drive_a =
		std::make_shared<SimFlashFsFlashMemory>( drive_a_path, DRIVE_A_FM_25_W_256_SIZE );
	mem_drive_b =
		std::make_shared<SimFlashFsFlashMemory>( drive_b_path, DRIVE_B_AT45_DB321E_SIZE );

	vfs    = std::make_shared<SimpleFlashFs::Vfs::SimpleFlashFsThreadedVfsServer>();
	drive_a = std::make_shared<FramFsDriveA>( mem_drive_a.get() );
	drive_b = std::make_shared<FramFsDriveB>( mem_drive_b.get() );

	vfs->register_drive( drive_a );
	vfs->register_drive( drive_b );
	vfs->start();

	parser = std::make_shared<SimpleFlashFs::Vfs::CommandParser>( vfs );

	using namespace SimpleFlashFs::Vfs;
	// Identical command set to two_drives_dynamic main.cc.
	parser->register_command( "ls",      std::make_shared<ListCommand>( vfs ) );
	parser->register_command( "dir",     std::make_shared<ListCommand>( vfs ), "" );
	parser->register_command( "cat",     std::make_shared<CatCommand>( vfs ) );
	parser->register_command( "cp",      std::make_shared<CopyCommand>( vfs ) );
	parser->register_command( "mv",      std::make_shared<MoveCommand>( vfs ) );
	parser->register_command( "rm",      std::make_shared<RemoveCommand>( vfs ) );
	parser->register_command( "touch",   std::make_shared<TouchCommand>( vfs ) );
	parser->register_command( "help",    std::make_shared<HelpCommand>( parser ), "?" );
	parser->register_command( "format",  std::make_shared<FormatCommand>( vfs ) );
	parser->register_command( "cd",      std::make_shared<ChangeDirectoryCommand>( vfs ) );
	parser->register_command( "pwd",     std::make_shared<PrintWorkingDirectoryCommand>( vfs ) );
	parser->register_command( "quit",    std::make_shared<TestCmdQuit>() );
	parser->register_command( "a:",      std::make_shared<DOSChangeDriveCommand>( vfs, "a" ) );
	parser->register_command( "b:",      std::make_shared<DOSChangeDriveCommand>( vfs, "b" ) );
	parser->register_command( "cleanup", std::make_shared<TestCmdCleanup>( vfs ) );
	parser->register_command( "test_count", std::make_shared<TestCount>( vfs ) );
}

VfsFixture::~VfsFixture()
{
	if( vfs ) {
		try {
			vfs->stop();
		} catch( ... ) {
			// destructor must not throw
		}
	}
	parser.reset();
	drive_a.reset();
	drive_b.reset();
	vfs.reset();

	// release simulators (closes the underlying fstream) before we
	// reopen the bin file for inspection in the calling test
	mem_drive_a.reset();
	mem_drive_b.reset();

	std::error_code ec;
	std::filesystem::remove( drive_a_path, ec );
	std::filesystem::remove( drive_b_path, ec );
}

VfsFixture::CmdSeqResult VfsFixture::run( const std::string & cmd_sequence )
{
	CmdSeqResult result;

	auto pieces = Tools::split_string_view( cmd_sequence, ";" );
	for( auto & raw : pieces ) {
		auto trimmed = Tools::strip( std::string( raw ) );
		if( trimmed.empty() ) {
			continue;
		}

		auto r = parser->execute_command_string( trimmed );
		result.output += r.output;
		if( !r.success ) {
			result.all_ok     = false;
			result.last_error = r.message;
			CPPDEBUG( Tools::format(
				"VfsFixture: command '%s' failed: %s", trimmed, r.message ) );
		}
		if( r.stop_execution ) {
			break;
		}
	}

	return result;
}

bool VfsFixture::reinit_drive( const std::string & drive_name )
{
	if( drive_name == "a" && drive_a ) {
		return drive_a->init();
	}
	if( drive_name == "b" && drive_b ) {
		return drive_b->init();
	}
	return false;
}
// AI generated by GitHub Copilot Claude Opus 4.7 END

// AI generated by GitHub Copilot Claude Opus 4.7 START
DriveInspect inspect_drive( const VfsFixture & fix,
                            const std::string & drive_name,
                            bool                pull_contents )
{
	DriveInspect info;

	std::string bin_path;
	if( drive_name == "a" ) {
		bin_path = fix.drive_a_path;
	} else if( drive_name == "b" ) {
		bin_path = fix.drive_b_path;
	} else {
		CPPDEBUG( Tools::format( "inspect_drive: unknown drive %s", drive_name ) );
		return info;
	}

	if( !std::filesystem::exists( bin_path ) ) {
		CPPDEBUG( Tools::format( "inspect_drive: missing bin file %s", bin_path ) );
		return info;
	}

	// The VFS server still owns the file handle on this bin file
	// (the simulator keeps the fstream open). The dynamic FS opens
	// its own independent fstream over the same path though - reads
	// see whatever was last flushed by the simulator. Every command
	// in this fixture's path either closes the handle (file goes
	// out of scope on command exit) or calls flush() before
	// returning, so we observe the on-disk state at command-sequence
	// completion.
	SimFlashFsFlashMemory inspect_mem( bin_path );
	::SimpleFlashFs::dynamic::SimpleFlashFsReadOnly inspect_fs( &inspect_mem );

	if( !inspect_fs.init() ) {
		CPPDEBUG( Tools::format( "inspect_drive: init failed on %s", bin_path ) );
		return info;
	}

	info.mounted         = true;
	info.free_data_pages = inspect_fs.get_number_of_free_data_pages();

	// Dedup by inode_number, keeping the highest inode_version_number
	// (COW leaves older versions on disk until lazy erase).
	// An inode whose latest version has an empty file_name is the
	// tombstone of a deleted file and is omitted.
	struct LatestEntry {
		std::shared_ptr<::SimpleFlashFs::dynamic::SimpleFlashFs::FileHandle> handle;
		uint64_t version = 0;
	};
	std::map<uint64_t, LatestEntry> latest_by_inode;

	for( auto inode : inspect_fs.get_all_inodes( false ) ) {
		if( !inode ) {
			continue;
		}
		uint64_t inum = inode->inode.inode_number;
		auto     it   = latest_by_inode.find( inum );
		if( it == latest_by_inode.end() ||
		    inode->inode.inode_version_number > it->second.version ) {
			latest_by_inode[inum] = { inode,
			                          inode->inode.inode_version_number };
		}
	}

	for( auto & [inum, entry] : latest_by_inode ) {
		if( entry.handle->inode.file_name.empty() ) {
			continue; // deleted file
		}
		DriveInspect::InodeView v;
		v.file_name        = entry.handle->inode.file_name;
		v.file_len         = entry.handle->inode.file_len;
		v.data_pages_count = entry.handle->inode.data_pages.size();
		v.inode_data_size  = entry.handle->inode.inode_data.size();
		v.inode_number     = entry.handle->inode.inode_number;
		v.inode_version    = entry.handle->inode.inode_version_number;
		v.page             = entry.handle->page;

		if( pull_contents && v.file_len > 0 ) {
			v.contents.resize( v.file_len );
			entry.handle->seek( 0 );
			std::size_t bytes_read =
				entry.handle->read( v.contents.data(), v.contents.size() );
			v.contents.resize( bytes_read );
		}

		info.inodes.push_back( std::move( v ) );
	}

	return info;
}

const DriveInspect::InodeView * find_file( const DriveInspect & info,
                                           const std::string_view & name )
{
	for( const auto & v : info.inodes ) {
		if( v.file_name == name ) {
			return &v;
		}
	}
	return nullptr;
}

bool bytes_equal( const std::vector<std::byte> & got,
                  const std::string_view &       expected,
                  const char *                   label )
{
	if( got.size() != expected.size() ) {
		CPPDEBUG( Tools::format( "%s: size mismatch got=%d expected=%d",
		                         label, got.size(), expected.size() ) );
		return false;
	}
	for( std::size_t i = 0; i < got.size(); i++ ) {
		if( static_cast<char>( got[i] ) != expected[i] ) {
			CPPDEBUG( Tools::format(
				"%s: byte mismatch at i=%d got=0x%02X expected=0x%02X",
				label, i, static_cast<unsigned>( got[i] ),
				static_cast<unsigned>( static_cast<unsigned char>( expected[i] ) ) ) );
			return false;
		}
	}
	return true;
}
// AI generated by GitHub Copilot Claude Opus 4.7 END

} // namespace test_vfs
