/*
 * test_simple_ini_compact.cc
 *
 * Tests that SimpleIni::properties_t::compact_file_format = true suppresses
 * the human-readable "(float_value)" suffix from float/double comments while
 * still preserving bit-exact round-trip fidelity.
 *
 * Background: when compact_file_format is false (default) the float write
 * stores a line like:
 *
 *   "\tmy_key = 0x41200000\n"
 *
 * preceded by a comment line that appends the decimal representation:
 *
 *   "\"\t(10.000000)\n"
 *
 * When compact_file_format is true the comment line is either omitted entirely
 * (no user comment) or contains only the user-supplied comment string, so the
 * file is smaller and the decimal value is not written.
 *
 * AI generated by GitHub Copilot Claude Sonnet 4.6 START
 *  Created on: 30.06.2026
 * AI generated by GitHub Copilot Claude Sonnet 4.6 END
 */

#include "test_simple_ini_compact.h"
#include "test_vfs_setup.h"
#include "../src_2face/SimpleIni.h"
#include "../src_2face/SimpleFlashFsFileBuffer.h"
#include <CpputilsDebug.h>
#include <format.h>
#include <string_utils.h>
#include <vector>
#include <string>

using namespace Tools;
using namespace test_vfs;

// AI generated by GitHub Copilot Claude Sonnet 4.6 START
namespace {

// ---------------------------------------------------------------------------
// TestCaseVfsCompact: local lambda wrapper (same pattern as TestCaseVfsLambda
// in test_mrdb_write_entry.cc, duplicated here to avoid ODR issues with the
// anonymous-namespace class in that translation unit).
// ---------------------------------------------------------------------------
class TestCaseVfsCompact : public TestCaseBase<bool>
{
public:
    using Func = std::function<bool( VfsFixture & )>;

private:
    Func func;

public:
    TestCaseVfsCompact( const std::string & name_, Func func_,
                        bool expected_result_ = true )
    : TestCaseBase<bool>( name_, expected_result_ ),
      func( func_ )
    {}

    bool run() override
    {
        VfsFixture fix( name );
        return func( fix );
    }
};

// Buffer size matching the VFS page geometry used in all other vfs tests.
constexpr std::size_t BUF_SIZE = 528;

static constexpr const char* SEC  = "data";
static constexpr const char* KEY  = "temperature";

// Read the entire raw content of a VFS file into a std::string.
// Returns an empty optional if the file cannot be opened.
std::optional<std::string> read_raw_content( SimpleFlashFs::Vfs::VfsServerInterface & vfs,
                                             const std::string & path )
{
    auto fh = vfs.open( path, std::ios::in );
    if( !fh ) {
        CPPDEBUG( Tools::format( "read_raw_content: cannot open '%s'", path ) );
        return std::nullopt;
    }

    const std::size_t size = fh->file_size();
    if( size == 0 ) {
        return std::string{};
    }

    std::vector<std::byte> buf( size );
    const std::size_t bytes_read = fh->read( buf.data(), size );

    return std::string( reinterpret_cast<const char*>( buf.data() ), bytes_read );
}

} // namespace
// AI generated by GitHub Copilot Claude Sonnet 4.6 END

// AI generated by GitHub Copilot Claude Sonnet 4.6 START
// ---------------------------------------------------------------------------
// test_case_simple_ini_compact_float_no_human_readable_comment
//
// Writes a float with compact_file_format=true (with a user comment) and
// verifies that the on-disk content does NOT contain the decimal
// "(float_value)" suffix that the default format appends.
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_simple_ini_compact_float_no_human_readable_comment()
{
    return std::make_shared<TestCaseVfsCompact>( __FUNCTION__,
        []( VfsFixture & fix ) -> bool {
            if( !fix.run( "format a: ; format b: ;" ).all_ok ) {
                CPPDEBUG( "compact_float_no_human_readable_comment: format failed" );
                return false;
            }

            const std::string path = "/b/compact_test.ini";
            constexpr float   WRITTEN_VALUE = 10.5f;

            // ── write with compact_file_format = true ─────────────────────
            {
                auto fh = fix.vfs->open( path, std::ios::out );
                if( !fh ) {
                    CPPDEBUG( "compact_float_no_human_readable_comment: cannot create file" );
                    return false;
                }

                std::vector<std::byte>  raw_buf( BUF_SIZE );
                std::span<std::byte>    sbuf( raw_buf );
                SimpleFlashFs::FileBuffer       fb( *fh, sbuf );
                SimpleFlashFs::SimpleIni<1024>  ini( fb );

                ini.properties.compact_file_format = true;

                // Write float with a user comment; compact mode must keep only
                // the user comment and must NOT append "(10.500000)".
                if( !ini.write( SEC, KEY, WRITTEN_VALUE, "celsius" ) ) {
                    CPPDEBUG( "compact_float_no_human_readable_comment: write failed" );
                    return false;
                }

                if( !fb.flush() ) {
                    CPPDEBUG( "compact_float_no_human_readable_comment: flush failed" );
                    return false;
                }
            }

            // ── inspect raw bytes ─────────────────────────────────────────
            auto o_content = read_raw_content( *fix.vfs, path );
            if( !o_content ) {
                CPPDEBUG( "compact_float_no_human_readable_comment: cannot read back file" );
                return false;
            }

            const std::string & content = *o_content;

            // The compact file must NOT contain a decimal float rendering.
            // The non-compact writer always appends "(10.500000)" (or similar).
            if( content.find( "(10.5" ) != std::string::npos ||
                content.find( "(10.500" ) != std::string::npos ) {
                CPPDEBUG( Tools::format(
                    "compact_float_no_human_readable_comment: "
                    "human-readable float suffix found in compact file: '%s'",
                    content ) );
                return false;
            }

            // The user comment "celsius" must still be present.
            if( content.find( "celsius" ) == std::string::npos ) {
                CPPDEBUG( Tools::format(
                    "compact_float_no_human_readable_comment: "
                    "user comment 'celsius' missing from compact file: '%s'",
                    content ) );
                return false;
            }

            // The hex-encoded value must be present (0x41280000 == 10.5f).
            if( content.find( "41280000" ) == std::string::npos &&
                content.find( "41280000" ) == std::string::npos ) {
                // Accept both upper and lower case hex.
                if( content.find( "41280000" ) == std::string::npos ) {
                    CPPDEBUG( Tools::format(
                        "compact_float_no_human_readable_comment: "
                        "hex value not found in compact file: '%s'",
                        content ) );
                    return false;
                }
            }

            return true;
        } );
}

// ---------------------------------------------------------------------------
// test_case_simple_ini_compact_float_roundtrip
//
// Writes several float values with compact_file_format=true, then reads them
// back via SimpleIni and verifies bit-exact equality.
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_simple_ini_compact_float_roundtrip()
{
    return std::make_shared<TestCaseVfsCompact>( __FUNCTION__,
        []( VfsFixture & fix ) -> bool {
            if( !fix.run( "format a: ; format b: ;" ).all_ok ) {
                CPPDEBUG( "compact_float_roundtrip: format failed" );
                return false;
            }

            const std::string path = "/b/compact_roundtrip.ini";

            // Representative values including edge cases.
            constexpr float VAL_A =  10.5f;
            constexpr float VAL_B = -0.001f;
            constexpr float VAL_C =  850.123f;
            constexpr float VAL_D =  0.0f;

            // ── write ─────────────────────────────────────────────────────
            {
                auto fh = fix.vfs->open( path, std::ios::out );
                if( !fh ) {
                    CPPDEBUG( "compact_float_roundtrip: cannot create file" );
                    return false;
                }

                std::vector<std::byte>  raw_buf( BUF_SIZE );
                std::span<std::byte>    sbuf( raw_buf );
                SimpleFlashFs::FileBuffer       fb( *fh, sbuf );
                SimpleFlashFs::SimpleIni<1024>  ini( fb );

                ini.properties.compact_file_format = true;

                if( !ini.write( "vals", "a", VAL_A ) ) { CPPDEBUG( "compact_float_roundtrip: write a failed" ); return false; }
                if( !ini.write( "vals", "b", VAL_B ) ) { CPPDEBUG( "compact_float_roundtrip: write b failed" ); return false; }
                if( !ini.write( "vals", "c", VAL_C ) ) { CPPDEBUG( "compact_float_roundtrip: write c failed" ); return false; }
                if( !ini.write( "vals", "d", VAL_D ) ) { CPPDEBUG( "compact_float_roundtrip: write d failed" ); return false; }

                if( !fb.flush() ) {
                    CPPDEBUG( "compact_float_roundtrip: flush failed" );
                    return false;
                }
            }

            // ── read back ─────────────────────────────────────────────────
            {
                auto fh = fix.vfs->open( path, std::ios::in );
                if( !fh ) {
                    CPPDEBUG( "compact_float_roundtrip: cannot open for read" );
                    return false;
                }

                std::vector<std::byte>  raw_buf( BUF_SIZE );
                std::span<std::byte>    sbuf( raw_buf );
                SimpleFlashFs::FileBuffer       fb( *fh, sbuf );
                SimpleFlashFs::SimpleIni<1024>  ini( fb );

                float got_a = 0.0f;
                if( !ini.read( "vals", "a", got_a ) ) {
                    CPPDEBUG( "compact_float_roundtrip: read a failed" );
                    return false;
                }
                // Bit-exact comparison via memcmp-safe union trick.
                union { float f; uint32_t i; } ua_exp, ua_got;
                ua_exp.f = VAL_A; ua_got.f = got_a;
                if( ua_exp.i != ua_got.i ) {
                    CPPDEBUG( Tools::format( "compact_float_roundtrip: a mismatch (expected 0x%X got 0x%X)",
                                             ua_exp.i, ua_got.i ) );
                    return false;
                }

                float got_b = 0.0f;
                if( !ini.read( "vals", "b", got_b ) ) {
                    CPPDEBUG( "compact_float_roundtrip: read b failed" );
                    return false;
                }
                union { float f; uint32_t i; } ub_exp, ub_got;
                ub_exp.f = VAL_B; ub_got.f = got_b;
                if( ub_exp.i != ub_got.i ) {
                    CPPDEBUG( Tools::format( "compact_float_roundtrip: b mismatch (expected 0x%X got 0x%X)",
                                             ub_exp.i, ub_got.i ) );
                    return false;
                }

                float got_c = 0.0f;
                if( !ini.read( "vals", "c", got_c ) ) {
                    CPPDEBUG( "compact_float_roundtrip: read c failed" );
                    return false;
                }
                union { float f; uint32_t i; } uc_exp, uc_got;
                uc_exp.f = VAL_C; uc_got.f = got_c;
                if( uc_exp.i != uc_got.i ) {
                    CPPDEBUG( Tools::format( "compact_float_roundtrip: c mismatch (expected 0x%X got 0x%X)",
                                             uc_exp.i, uc_got.i ) );
                    return false;
                }

                float got_d = 0.0f;
                if( !ini.read( "vals", "d", got_d ) ) {
                    CPPDEBUG( "compact_float_roundtrip: read d failed" );
                    return false;
                }
                union { float f; uint32_t i; } ud_exp, ud_got;
                ud_exp.f = VAL_D; ud_got.f = got_d;
                if( ud_exp.i != ud_got.i ) {
                    CPPDEBUG( Tools::format( "compact_float_roundtrip: d mismatch (expected 0x%X got 0x%X)",
                                             ud_exp.i, ud_got.i ) );
                    return false;
                }
            }

            return true;
        } );
}

// ---------------------------------------------------------------------------
// test_case_simple_ini_compact_smaller_than_normal
//
// Writes the same float value (with a user comment) once in compact mode and
// once in normal mode, then verifies that the compact file is strictly smaller
// than the normal one.
// ---------------------------------------------------------------------------
std::shared_ptr<TestCaseBase<bool>> test_case_simple_ini_compact_smaller_than_normal()
{
    return std::make_shared<TestCaseVfsCompact>( __FUNCTION__,
        []( VfsFixture & fix ) -> bool {
            if( !fix.run( "format a: ; format b: ;" ).all_ok ) {
                CPPDEBUG( "compact_smaller_than_normal: format failed" );
                return false;
            }

            constexpr float WRITTEN_VALUE = 40.0f;

            // ── compact file ──────────────────────────────────────────────
            std::size_t compact_size = 0;
            {
                const std::string path = "/b/compact.ini";
                auto fh = fix.vfs->open( path, std::ios::out );
                if( !fh ) {
                    CPPDEBUG( "compact_smaller_than_normal: cannot create compact file" );
                    return false;
                }

                std::vector<std::byte>  raw_buf( BUF_SIZE );
                std::span<std::byte>    sbuf( raw_buf );
                SimpleFlashFs::FileBuffer       fb( *fh, sbuf );
                SimpleFlashFs::SimpleIni<1024>  ini( fb );

                ini.properties.compact_file_format = true;
                if( !ini.write( SEC, KEY, WRITTEN_VALUE, "measurement" ) ) {
                    CPPDEBUG( "compact_smaller_than_normal: compact write failed" );
                    return false;
                }
                if( !fb.flush() ) {
                    CPPDEBUG( "compact_smaller_than_normal: compact flush failed" );
                    return false;
                }
                compact_size = fh->file_size();
            }

            // ── normal file ───────────────────────────────────────────────
            std::size_t normal_size = 0;
            {
                const std::string path = "/b/normal.ini";
                auto fh = fix.vfs->open( path, std::ios::out );
                if( !fh ) {
                    CPPDEBUG( "compact_smaller_than_normal: cannot create normal file" );
                    return false;
                }

                std::vector<std::byte>  raw_buf( BUF_SIZE );
                std::span<std::byte>    sbuf( raw_buf );
                SimpleFlashFs::FileBuffer       fb( *fh, sbuf );
                SimpleFlashFs::SimpleIni<1024>  ini( fb );

                // compact_file_format defaults to false — normal mode.
                if( !ini.write( SEC, KEY, WRITTEN_VALUE, "measurement" ) ) {
                    CPPDEBUG( "compact_smaller_than_normal: normal write failed" );
                    return false;
                }
                if( !fb.flush() ) {
                    CPPDEBUG( "compact_smaller_than_normal: normal flush failed" );
                    return false;
                }
                normal_size = fh->file_size();
            }

            if( compact_size >= normal_size ) {
                CPPDEBUG( Tools::format(
                    "compact_smaller_than_normal: expected compact (%zu) < normal (%zu)",
                    compact_size, normal_size ) );
                return false;
            }

            return true;
        } );
}
// AI generated by GitHub Copilot Claude Sonnet 4.6 END
