/**
 * SimpleFlashFs direct (non-wrapper) test cases.
 *
 * AI generated by GitHub Copilot Claude Opus 4.7 START
 */
#include "test_dynamic_direct.h"

#include <SimpleFlashFsDynamic.h>
#include <stderr_exception.h>
#include <format.h>
#include <CpputilsDebug.h>
#include <SimFlashMemoryPc.h>

#include <ios>
#include <string>
#include <vector>
#include <cstddef>
#include <cstring>
#include <cstdint>

using namespace Tools;
using namespace SimpleFlashFs;
using namespace SimpleFlashFs::dynamic;
using namespace SimpleFlashFs::SimPc;

namespace {

// Drive A geometry, matching simpleflashfs/src_vfs/main.cc:
//   constexpr uint32_t DRIVE_A_FM_25_W_256_SIZE      = 0x00007FFF + 1; // 32 KB
//   constexpr uint32_t DRIVE_A_FM_25_W_256_PAGE_SIZE = 256;
constexpr std::size_t DRIVE_A_SIZE      = 0x00007FFF + 1;
constexpr std::size_t DRIVE_A_PAGE_SIZE = 256;

// A simple counter to give every instance its own backing file.
unsigned direct_instance_count = 0;

/**
 * Common bring-up code for tests that hit the dynamic FS directly.
 *
 * Each test owns its own backing file (".direct_testN.bin") so multiple
 * instances can coexist without interfering with one another.
 */
class TestCaseDirectBase : public TestCaseBase<bool>
{
protected:
	std::size_t page_size;
	std::size_t size;
	std::string backing_file;
	std::shared_ptr<SimFlashFsFlashMemory> mem;
	std::shared_ptr<SimpleFlashFs::dynamic::SimpleFlashFs> fs;

public:
	TestCaseDirectBase( const std::string & name_,
			std::size_t page_size_ = DRIVE_A_PAGE_SIZE,
			std::size_t size_ = DRIVE_A_SIZE,
			bool expected_result_ = true,
			bool exception_ = false )
	: TestCaseBase<bool>( name_, expected_result_, exception_ ),
	  page_size( page_size_ ),
	  size( size_ ),
	  backing_file( Tools::format( ".direct_test%d.bin", direct_instance_count++ ) )
	{
	}

	bool init()
	{
		mem = std::make_shared<SimFlashFsFlashMemory>( backing_file, size );
		fs  = std::make_shared<SimpleFlashFs::dynamic::SimpleFlashFs>( mem.get() );

		if( !fs->create(fs->create_default_header(page_size, size / page_size)) ) {
			throw STDERR_EXCEPTION( Tools::format( "cannot create %s", backing_file ) );
		}

		return true;
	}
};

/**
 * Reproduces the failure of `run test1`:
 *   format a: ; a: ; test_count count 74 ; cat count
 *
 * Steps (per iteration i = 1..max_val):
 *   1) Open file in (out | app) mode -- same flags as TestCount::execute().
 *   2) Write "<i>\n".
 *   3) Let the FileHandle go out of scope so its destructor flushes.
 *
 * Verification mirrors `CatCommand::execute()`: open (in | binary), read all
 * bytes into a buffer, then walk it and check that line N equals "<N>\n".
 */
class TestCaseCountCat : public TestCaseDirectBase
{
	uint32_t max_val;

public:
	TestCaseCountCat( const std::string & name_, uint32_t max_val_ = 74 )
	: TestCaseDirectBase( name_ ),
	  max_val( max_val_ )
	{
	}

	bool run() override
	{
		if( !init() ) {
			CPPDEBUG( "init failed" );
			return false;
		}

		const std::string filename = "count";

		// ---- Phase 1: write (mirrors test_count) -----------------------
		for( uint32_t i = 1; i <= max_val; i++ ) {
			const std::string content = std::to_string(i) + "\n";

			auto handle = fs->open( filename,
			                        std::ios_base::out | std::ios_base::app );
			if( !handle ) {
				CPPDEBUG( Tools::format( "cannot open '%s' for append at i=%d",
				                         filename, i ) );
				return false;
			}

			const std::byte * data = reinterpret_cast<const std::byte*>( content.data() );
			const std::size_t written = handle.write( data, content.size() );

			if( written != content.size() ) {
				CPPDEBUG( Tools::format( "write returned %d, expected %d at i=%d",
				                         written, content.size(), i ) );
				return false;
			}

			// Destructor of FileHandle flushes on scope exit.
		}

		// ---- Phase 2: read everything back (mirrors cat) ----------------
		std::vector<std::byte> raw;
		{
			auto handle = fs->open( filename, std::ios_base::in );
			if( !handle ) {
				CPPDEBUG( Tools::format( "cannot open '%s' for reading", filename ) );
				return false;
			}

			const std::size_t file_len = handle.file_size();
			raw.resize( file_len );

			if( file_len > 0 ) {
				const std::size_t read_bytes = handle.read( raw.data(), file_len );
				if( read_bytes != file_len ) {
					CPPDEBUG( Tools::format( "short read: got %d of %d bytes",
					                         read_bytes, file_len ) );
					return false;
				}
			}
		}

		const std::string content( reinterpret_cast<const char*>(raw.data()),
		                           raw.size() );

		// ---- Phase 3: validate every line ------------------------------
		std::size_t pos = 0;
		for( uint32_t i = 1; i <= max_val; i++ ) {
			const std::string expected = std::to_string(i) + "\n";

			if( pos + expected.size() > content.size() ) {
				CPPDEBUG( Tools::format(
					"truncated at i=%d: pos=%d need %d but total=%d",
					i, pos, expected.size(), content.size() ) );
				CPPDEBUG( Tools::format( "tail of content: '%s'",
					content.substr( pos < content.size() ? pos : content.size() ) ) );
				return false;
			}

			const std::string got = content.substr( pos, expected.size() );
			if( got != expected ) {
				auto hex = []( const std::string & s ) {
					std::string out;
					for( unsigned char c : s ) {
						out += Tools::format( "%02x ", static_cast<unsigned>(c) );
					}
					return out;
				};
				CPPDEBUG( Tools::format(
					"line mismatch at i=%d: got hex=[%s] expected hex=[%s] (pos=%d, total=%d)",
					i, hex(got), hex(expected), pos, content.size() ) );
				// Show context to make the off-by-one obvious in test output.
				const std::size_t ctx_start = pos > 8 ? pos - 8 : 0;
				const std::size_t ctx_end   = std::min( pos + 16, content.size() );
				const std::string ctx = content.substr( ctx_start, ctx_end - ctx_start );
				CPPDEBUG( Tools::format( "context [%d..%d) hex=[%s]",
					ctx_start, ctx_end, hex(ctx) ) );
				return false;
			}

			pos += expected.size();
		}

		if( pos != content.size() ) {
			CPPDEBUG( Tools::format( "trailing garbage: pos=%d total=%d tail='%s'",
				pos, content.size(), content.substr(pos) ) );
			return false;
		}

		return true;
	}
};

} // namespace

std::shared_ptr<TestCaseBase<bool>> test_case_direct_test_count_cat()
{
	return std::make_shared<TestCaseCountCat>( "direct_test_count_cat", 74 );
}
// AI generated by GitHub Copilot Claude Opus 4.7 END
