/**
 * SimpleFlashFs direct (non-wrapper) test cases.
 *
 * These tests exercise the SimpleFlashFs::dynamic::SimpleFlashFs API directly
 * (the same path that two_drives_dynamic's `test_count` + `cat` use), so they
 * reproduce bugs that the C-style fopen/fwrite/fgets wrapper might mask.
 *
 * AI generated by GitHub Copilot Claude Opus 4.7 START
 */
#ifndef TEST_DYNAMIC_TEST_DYNAMIC_DIRECT_H_
#define TEST_DYNAMIC_TEST_DYNAMIC_DIRECT_H_

#include <TestUtils.h>
#include <memory>

// Mirrors `two_drives_dynamic` test1:
//   format a: ; a: ; test_count count 74 ; cat count
// Uses Drive A geometry (256-byte pages, 32 KB total), opens the file in
// append mode for each number, writes "<i>\n", then reads everything back as
// raw bytes (like cat) and checks that every line is intact.
std::shared_ptr<TestCaseBase<bool>> test_case_direct_test_count_cat();

#endif /* TEST_DYNAMIC_TEST_DYNAMIC_DIRECT_H_ */
// AI generated by GitHub Copilot Claude Opus 4.7 END
